"""phase 1b operational mirror

Revision ID: c0188f6a1ce5
Revises: 20260724_0001
Create Date: 2026-08-07 16:59:57.183972
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "c0188f6a1ce5"
down_revision: str | None = "20260724_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("forced", sa.Boolean(), nullable=False),
        sa.Column("source_name", sa.String(length=255), nullable=True),
        sa.Column("source_size", sa.BigInteger(), nullable=True),
        sa.Column("source_modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_sha256", sa.String(length=64), nullable=True),
        sa.Column("counters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_type", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sync_runs_source_sha256"), "sync_runs", ["source_sha256"], unique=False
    )
    op.create_index(op.f("ix_sync_runs_status"), "sync_runs", ["status"], unique=False)
    op.create_table(
        "operational_import_batches",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("sync_run_id", sa.BigInteger(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("counters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["sync_run_id"], ["sync_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_operational_import_batches_source_sha256"),
        "operational_import_batches",
        ["source_sha256"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operational_import_batches_sync_run_id"),
        "operational_import_batches",
        ["sync_run_id"],
        unique=False,
    )
    op.create_table(
        "data_inconsistencies",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("sync_run_id", sa.BigInteger(), nullable=False),
        sa.Column("import_batch_id", sa.BigInteger(), nullable=True),
        sa.Column("source_sheet", sa.String(length=80), nullable=False),
        sa.Column("source_row_number", sa.Integer(), nullable=True),
        sa.Column("inconsistency_type", sa.String(length=80), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("masked_value", sa.Text(), nullable=True),
        sa.Column("review_status", sa.String(length=24), server_default="pending", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id"], ["operational_import_batches.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["sync_run_id"], ["sync_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_inconsistencies_import_batch_id"),
        "data_inconsistencies",
        ["import_batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_inconsistencies_inconsistency_type"),
        "data_inconsistencies",
        ["inconsistency_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_inconsistencies_sync_run_id"),
        "data_inconsistencies",
        ["sync_run_id"],
        unique=False,
    )
    op.create_table(
        "excel_bcli_cadastro_rows",
        sa.Column("cod_cliente_original", sa.Text(), nullable=True),
        sa.Column("cod_cliente", sa.String(length=100), nullable=True),
        sa.Column("cpf_original", sa.Text(), nullable=True),
        sa.Column("cpf_normalized", sa.String(length=11), nullable=True),
        sa.Column("nome_cliente_original", sa.Text(), nullable=True),
        sa.Column("nome_cliente", sa.Text(), nullable=True),
        sa.Column("dt_nasc_original", sa.Text(), nullable=True),
        sa.Column("dt_nasc", sa.Date(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("import_batch_id", sa.BigInteger(), nullable=False),
        sa.Column("source_sheet", sa.String(length=80), nullable=False),
        sa.Column("source_row_number", sa.Integer(), nullable=False),
        sa.Column("source_row_hash", sa.String(length=64), nullable=False),
        sa.Column("source_key", sa.String(length=255), nullable=True),
        sa.Column("validation_status", sa.String(length=24), nullable=False),
        sa.Column("validation_errors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "imported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_seen_batch_id", sa.BigInteger(), nullable=False),
        sa.Column("source_active", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["import_batch_id"], ["operational_import_batches.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["last_seen_batch_id"],
            ["operational_import_batches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_excel_bcli_cadastro_rows_cod_cliente"),
        "excel_bcli_cadastro_rows",
        ["cod_cliente"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excel_bcli_cadastro_rows_cpf_normalized"),
        "excel_bcli_cadastro_rows",
        ["cpf_normalized"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excel_bcli_cadastro_rows_import_batch_id"),
        "excel_bcli_cadastro_rows",
        ["import_batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excel_bcli_cadastro_rows_last_seen_batch_id"),
        "excel_bcli_cadastro_rows",
        ["last_seen_batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excel_bcli_cadastro_rows_source_active"),
        "excel_bcli_cadastro_rows",
        ["source_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excel_bcli_cadastro_rows_source_key"),
        "excel_bcli_cadastro_rows",
        ["source_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excel_bcli_cadastro_rows_source_row_hash"),
        "excel_bcli_cadastro_rows",
        ["source_row_hash"],
        unique=False,
    )
    op.create_table(
        "excel_dfen_contrato_rows",
        sa.Column("cod_cliente", sa.String(length=100), nullable=True),
        sa.Column("cod_contrato", sa.String(length=100), nullable=True),
        sa.Column("cpf_original", sa.Text(), nullable=True),
        sa.Column("cpf_normalized", sa.String(length=11), nullable=True),
        sa.Column("dt_operacao", sa.Date(), nullable=True),
        sa.Column("vcto_prim_parc", sa.Date(), nullable=True),
        sa.Column("prazo", sa.Integer(), nullable=True),
        sa.Column("principal", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("iof", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("vl_financiado", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("pmt", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("vl_liberado", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("data_liberacao", sa.Date(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("import_batch_id", sa.BigInteger(), nullable=False),
        sa.Column("source_sheet", sa.String(length=80), nullable=False),
        sa.Column("source_row_number", sa.Integer(), nullable=False),
        sa.Column("source_row_hash", sa.String(length=64), nullable=False),
        sa.Column("source_key", sa.String(length=255), nullable=True),
        sa.Column("validation_status", sa.String(length=24), nullable=False),
        sa.Column("validation_errors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "imported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_seen_batch_id", sa.BigInteger(), nullable=False),
        sa.Column("source_active", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["import_batch_id"], ["operational_import_batches.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["last_seen_batch_id"],
            ["operational_import_batches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_excel_dfen_contrato_rows_cod_cliente"),
        "excel_dfen_contrato_rows",
        ["cod_cliente"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excel_dfen_contrato_rows_cod_contrato"),
        "excel_dfen_contrato_rows",
        ["cod_contrato"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excel_dfen_contrato_rows_cpf_normalized"),
        "excel_dfen_contrato_rows",
        ["cpf_normalized"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excel_dfen_contrato_rows_import_batch_id"),
        "excel_dfen_contrato_rows",
        ["import_batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excel_dfen_contrato_rows_last_seen_batch_id"),
        "excel_dfen_contrato_rows",
        ["last_seen_batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excel_dfen_contrato_rows_source_active"),
        "excel_dfen_contrato_rows",
        ["source_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excel_dfen_contrato_rows_source_key"),
        "excel_dfen_contrato_rows",
        ["source_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excel_dfen_contrato_rows_source_row_hash"),
        "excel_dfen_contrato_rows",
        ["source_row_hash"],
        unique=False,
    )
    op.create_table(
        "excel_econ_amortizacoes_rows",
        sa.Column("cod_cliente", sa.String(length=100), nullable=True),
        sa.Column("cpf_original", sa.Text(), nullable=True),
        sa.Column("cpf_normalized", sa.String(length=11), nullable=True),
        sa.Column("cod_contrato", sa.String(length=100), nullable=True),
        sa.Column("cod_parcela", sa.String(length=100), nullable=True),
        sa.Column("vencimento", sa.Date(), nullable=True),
        sa.Column("val_amtz_jur", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("val_amtz_princ", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("val_parcela", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("baixa_total", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("dt_baixatotal", sa.Date(), nullable=True),
        sa.Column("val_pgto", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("desconto_conc", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("status_parc", sa.Text(), nullable=True),
        sa.Column("situacao", sa.Text(), nullable=True),
        sa.Column("chave_referencia", sa.Text(), nullable=True),
        sa.Column("bol_antecip", sa.Text(), nullable=True),
        sa.Column("produto_financeiro", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("import_batch_id", sa.BigInteger(), nullable=False),
        sa.Column("source_sheet", sa.String(length=80), nullable=False),
        sa.Column("source_row_number", sa.Integer(), nullable=False),
        sa.Column("source_row_hash", sa.String(length=64), nullable=False),
        sa.Column("source_key", sa.String(length=255), nullable=True),
        sa.Column("validation_status", sa.String(length=24), nullable=False),
        sa.Column("validation_errors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "imported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_seen_batch_id", sa.BigInteger(), nullable=False),
        sa.Column("source_active", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["import_batch_id"], ["operational_import_batches.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["last_seen_batch_id"],
            ["operational_import_batches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_excel_econ_amortizacoes_contract_installment",
        "excel_econ_amortizacoes_rows",
        ["cod_contrato", "cod_parcela"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excel_econ_amortizacoes_rows_cod_cliente"),
        "excel_econ_amortizacoes_rows",
        ["cod_cliente"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excel_econ_amortizacoes_rows_cod_contrato"),
        "excel_econ_amortizacoes_rows",
        ["cod_contrato"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excel_econ_amortizacoes_rows_cpf_normalized"),
        "excel_econ_amortizacoes_rows",
        ["cpf_normalized"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excel_econ_amortizacoes_rows_import_batch_id"),
        "excel_econ_amortizacoes_rows",
        ["import_batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excel_econ_amortizacoes_rows_last_seen_batch_id"),
        "excel_econ_amortizacoes_rows",
        ["last_seen_batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excel_econ_amortizacoes_rows_source_active"),
        "excel_econ_amortizacoes_rows",
        ["source_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excel_econ_amortizacoes_rows_source_key"),
        "excel_econ_amortizacoes_rows",
        ["source_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excel_econ_amortizacoes_rows_source_row_hash"),
        "excel_econ_amortizacoes_rows",
        ["source_row_hash"],
        unique=False,
    )
    op.create_table(
        "excel_econ_emprestimos_rows",
        sa.Column("cod_contrato", sa.String(length=100), nullable=True),
        sa.Column("cod_cliente", sa.String(length=100), nullable=True),
        sa.Column("cpf_original", sa.Text(), nullable=True),
        sa.Column("cpf_normalized", sa.String(length=11), nullable=True),
        sa.Column("dt_operacao", sa.Date(), nullable=True),
        sa.Column("vencimento1", sa.Date(), nullable=True),
        sa.Column("vl_principal", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("prazo_pgto", sa.Integer(), nullable=True),
        sa.Column("iof", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("vl_finaciado", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("pmt", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("vl_liberado", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("taxa_juros", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("taxa_tir", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("taxa_cet_am", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("import_batch_id", sa.BigInteger(), nullable=False),
        sa.Column("source_sheet", sa.String(length=80), nullable=False),
        sa.Column("source_row_number", sa.Integer(), nullable=False),
        sa.Column("source_row_hash", sa.String(length=64), nullable=False),
        sa.Column("source_key", sa.String(length=255), nullable=True),
        sa.Column("validation_status", sa.String(length=24), nullable=False),
        sa.Column("validation_errors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "imported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_seen_batch_id", sa.BigInteger(), nullable=False),
        sa.Column("source_active", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["import_batch_id"], ["operational_import_batches.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["last_seen_batch_id"],
            ["operational_import_batches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_excel_econ_emprestimos_rows_cod_cliente"),
        "excel_econ_emprestimos_rows",
        ["cod_cliente"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excel_econ_emprestimos_rows_cod_contrato"),
        "excel_econ_emprestimos_rows",
        ["cod_contrato"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excel_econ_emprestimos_rows_cpf_normalized"),
        "excel_econ_emprestimos_rows",
        ["cpf_normalized"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excel_econ_emprestimos_rows_import_batch_id"),
        "excel_econ_emprestimos_rows",
        ["import_batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excel_econ_emprestimos_rows_last_seen_batch_id"),
        "excel_econ_emprestimos_rows",
        ["last_seen_batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excel_econ_emprestimos_rows_source_active"),
        "excel_econ_emprestimos_rows",
        ["source_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excel_econ_emprestimos_rows_source_key"),
        "excel_econ_emprestimos_rows",
        ["source_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excel_econ_emprestimos_rows_source_row_hash"),
        "excel_econ_emprestimos_rows",
        ["source_row_hash"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_excel_econ_emprestimos_rows_source_row_hash"),
        table_name="excel_econ_emprestimos_rows",
    )
    op.drop_index(
        op.f("ix_excel_econ_emprestimos_rows_source_key"), table_name="excel_econ_emprestimos_rows"
    )
    op.drop_index(
        op.f("ix_excel_econ_emprestimos_rows_source_active"),
        table_name="excel_econ_emprestimos_rows",
    )
    op.drop_index(
        op.f("ix_excel_econ_emprestimos_rows_last_seen_batch_id"),
        table_name="excel_econ_emprestimos_rows",
    )
    op.drop_index(
        op.f("ix_excel_econ_emprestimos_rows_import_batch_id"),
        table_name="excel_econ_emprestimos_rows",
    )
    op.drop_index(
        op.f("ix_excel_econ_emprestimos_rows_cpf_normalized"),
        table_name="excel_econ_emprestimos_rows",
    )
    op.drop_index(
        op.f("ix_excel_econ_emprestimos_rows_cod_contrato"),
        table_name="excel_econ_emprestimos_rows",
    )
    op.drop_index(
        op.f("ix_excel_econ_emprestimos_rows_cod_cliente"), table_name="excel_econ_emprestimos_rows"
    )
    op.drop_table("excel_econ_emprestimos_rows")
    op.drop_index(
        op.f("ix_excel_econ_amortizacoes_rows_source_row_hash"),
        table_name="excel_econ_amortizacoes_rows",
    )
    op.drop_index(
        op.f("ix_excel_econ_amortizacoes_rows_source_key"),
        table_name="excel_econ_amortizacoes_rows",
    )
    op.drop_index(
        op.f("ix_excel_econ_amortizacoes_rows_source_active"),
        table_name="excel_econ_amortizacoes_rows",
    )
    op.drop_index(
        op.f("ix_excel_econ_amortizacoes_rows_last_seen_batch_id"),
        table_name="excel_econ_amortizacoes_rows",
    )
    op.drop_index(
        op.f("ix_excel_econ_amortizacoes_rows_import_batch_id"),
        table_name="excel_econ_amortizacoes_rows",
    )
    op.drop_index(
        op.f("ix_excel_econ_amortizacoes_rows_cpf_normalized"),
        table_name="excel_econ_amortizacoes_rows",
    )
    op.drop_index(
        op.f("ix_excel_econ_amortizacoes_rows_cod_contrato"),
        table_name="excel_econ_amortizacoes_rows",
    )
    op.drop_index(
        op.f("ix_excel_econ_amortizacoes_rows_cod_cliente"),
        table_name="excel_econ_amortizacoes_rows",
    )
    op.drop_index(
        "ix_excel_econ_amortizacoes_contract_installment", table_name="excel_econ_amortizacoes_rows"
    )
    op.drop_table("excel_econ_amortizacoes_rows")
    op.drop_index(
        op.f("ix_excel_dfen_contrato_rows_source_row_hash"), table_name="excel_dfen_contrato_rows"
    )
    op.drop_index(
        op.f("ix_excel_dfen_contrato_rows_source_key"), table_name="excel_dfen_contrato_rows"
    )
    op.drop_index(
        op.f("ix_excel_dfen_contrato_rows_source_active"), table_name="excel_dfen_contrato_rows"
    )
    op.drop_index(
        op.f("ix_excel_dfen_contrato_rows_last_seen_batch_id"),
        table_name="excel_dfen_contrato_rows",
    )
    op.drop_index(
        op.f("ix_excel_dfen_contrato_rows_import_batch_id"), table_name="excel_dfen_contrato_rows"
    )
    op.drop_index(
        op.f("ix_excel_dfen_contrato_rows_cpf_normalized"), table_name="excel_dfen_contrato_rows"
    )
    op.drop_index(
        op.f("ix_excel_dfen_contrato_rows_cod_contrato"), table_name="excel_dfen_contrato_rows"
    )
    op.drop_index(
        op.f("ix_excel_dfen_contrato_rows_cod_cliente"), table_name="excel_dfen_contrato_rows"
    )
    op.drop_table("excel_dfen_contrato_rows")
    op.drop_index(
        op.f("ix_excel_bcli_cadastro_rows_source_row_hash"), table_name="excel_bcli_cadastro_rows"
    )
    op.drop_index(
        op.f("ix_excel_bcli_cadastro_rows_source_key"), table_name="excel_bcli_cadastro_rows"
    )
    op.drop_index(
        op.f("ix_excel_bcli_cadastro_rows_source_active"), table_name="excel_bcli_cadastro_rows"
    )
    op.drop_index(
        op.f("ix_excel_bcli_cadastro_rows_last_seen_batch_id"),
        table_name="excel_bcli_cadastro_rows",
    )
    op.drop_index(
        op.f("ix_excel_bcli_cadastro_rows_import_batch_id"), table_name="excel_bcli_cadastro_rows"
    )
    op.drop_index(
        op.f("ix_excel_bcli_cadastro_rows_cpf_normalized"), table_name="excel_bcli_cadastro_rows"
    )
    op.drop_index(
        op.f("ix_excel_bcli_cadastro_rows_cod_cliente"), table_name="excel_bcli_cadastro_rows"
    )
    op.drop_table("excel_bcli_cadastro_rows")
    op.drop_index(op.f("ix_data_inconsistencies_sync_run_id"), table_name="data_inconsistencies")
    op.drop_index(
        op.f("ix_data_inconsistencies_inconsistency_type"), table_name="data_inconsistencies"
    )
    op.drop_index(
        op.f("ix_data_inconsistencies_import_batch_id"), table_name="data_inconsistencies"
    )
    op.drop_table("data_inconsistencies")
    op.drop_index(
        op.f("ix_operational_import_batches_sync_run_id"), table_name="operational_import_batches"
    )
    op.drop_index(
        op.f("ix_operational_import_batches_source_sha256"), table_name="operational_import_batches"
    )
    op.drop_table("operational_import_batches")
    op.drop_index(op.f("ix_sync_runs_status"), table_name="sync_runs")
    op.drop_index(op.f("ix_sync_runs_source_sha256"), table_name="sync_runs")
    op.drop_table("sync_runs")
    # ### end Alembic commands ###
