"""phase 1b2 business rules and utc durations

Revision ID: ecacd0239c1a
Revises: c0188f6a1ce5
Create Date: 2026-08-07 18:10:40.114989
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ecacd0239c1a"
down_revision: str | None = "c0188f6a1ce5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_inconsistencies", sa.Column("severity", sa.String(length=24), nullable=True)
    )
    op.create_index(
        op.f("ix_data_inconsistencies_severity"), "data_inconsistencies", ["severity"], unique=False
    )
    op.add_column(
        "excel_econ_amortizacoes_rows", sa.Column("baixa_total_original", sa.Text(), nullable=True)
    )
    op.add_column(
        "operational_import_batches", sa.Column("duration_ms", sa.BigInteger(), nullable=True)
    )
    op.add_column("sync_runs", sa.Column("duration_ms", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sync_runs", "duration_ms")
    op.drop_column("operational_import_batches", "duration_ms")
    op.drop_column("excel_econ_amortizacoes_rows", "baixa_total_original")
    op.drop_index(op.f("ix_data_inconsistencies_severity"), table_name="data_inconsistencies")
    op.drop_column("data_inconsistencies", "severity")
    # ### end Alembic commands ###
