import { Check, Plus, RefreshCw } from "lucide-react";
import { useState } from "react";
import { FeedbackBanner, type Feedback } from "@/components/common/FeedbackBanner";
import { FormField } from "@/components/common/FormField";
import { Modal } from "@/components/common/Modal";
import { PageHeader } from "@/components/common/PageHeader";
import { StatusBadge } from "@/components/common/StatusBadge";
import { PaymentConfirmationModal } from "@/components/funding/PaymentConfirmationModal";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { currencyInputToCents, formatCentsAmount, formatDate, formatDateTime } from "@/lib/formatters";
import { fundingRepository, useFundingState } from "@/services/fundingService";
import type { CapitalRemunerationInput, PaymentBatchInput } from "@/types/funding";

export function CapitalRemunerationsPage({ id }: { id?: string }) {
  const state = useFundingState(); const [createOpen, setCreateOpen] = useState(false); const [payIds, setPayIds] = useState<string[]>([]); const [reinvestId, setReinvestId] = useState<string | null>(null); const [feedback, setFeedback] = useState<Feedback | null>(null);
  const rows = id ? state.capitalRemunerationEvents.filter((item) => item.id === id) : state.capitalRemunerationEvents;
  const investorName = (value: string) => state.investors.find((item) => item.id === value)?.name ?? "—"; const contributionCode = (value: string) => state.contributions.find((item) => item.id === value)?.code ?? "—";
  const pay = (input: PaymentBatchInput) => { try { fundingRepository.payCapitalRemunerations(input); setPayIds([]); setFeedback({ tone: "success", message: "Pagamento registrado com saída e auditoria." }); } catch (error) { setFeedback({ tone: "error", message: error instanceof Error ? error.message : "Falha no pagamento." }); } };
  return <div className="space-y-6"><PageHeader eyebrow="Cadastro" title={id ? "Detalhe da Remuneração de Capital" : "Remuneração de Capital"} description="Valor originalmente aportado × taxa mensal contratada. PJR informado; regra definitiva fora do escopo." actions={!id && <Button onClick={() => setCreateOpen(true)}><Plus className="size-4" />Novo evento</Button>} /><FeedbackBanner feedback={feedback} onClose={() => setFeedback(null)} />
    <Card className="overflow-hidden bg-card/75"><Table><TableHeader><TableRow><TableHead>Investidor / aporte</TableHead><TableHead>Competência</TableHead><TableHead>Base e taxa</TableHead><TableHead>Bruto</TableHead><TableHead>PJR informado</TableHead><TableHead>Líquido</TableHead><TableHead>Datas</TableHead><TableHead>Status</TableHead><TableHead>Liquidação</TableHead><TableHead>Ações</TableHead></TableRow></TableHeader><TableBody>{rows.map((item) => <TableRow key={item.id}><TableCell>{investorName(item.investorId)}<p className="text-xs text-muted-foreground">{contributionCode(item.contributionId)}</p></TableCell><TableCell>{item.competence}</TableCell><TableCell>{formatCentsAmount(item.originalContributionAmount)}<p className="text-xs text-muted-foreground">Base original · {item.monthlyRateBps} bps</p></TableCell><TableCell>{formatCentsAmount(item.grossAmount)}</TableCell><TableCell>{formatCentsAmount(item.informedPjrAmount)}</TableCell><TableCell>{formatCentsAmount(item.netAmount)}</TableCell><TableCell>{formatDate(item.expectedDate)}<p className="text-xs text-muted-foreground">Pago: {formatDate(item.paymentDate)}</p></TableCell><TableCell><StatusBadge status={item.status} /></TableCell><TableCell>{item.settlementMethod.replaceAll("_", " ")}</TableCell><TableCell>{["PREVISTA", "A_VENCER", "VENCE_HOJE", "ATRASADA"].includes(item.status) && <div className="flex gap-1"><Button size="icon" variant="ghost" onClick={() => setPayIds([item.id])} title="Pagar"><Check className="size-4" /></Button><Button size="icon" variant="ghost" onClick={() => setReinvestId(item.id)} title="Reinvestir"><RefreshCw className="size-4" /></Button></div>}</TableCell></TableRow>)}</TableBody></Table></Card>
    {id && rows[0] && <Card className="bg-card/75"><CardHeader><CardTitle className="text-base">Observações e histórico</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">{rows[0].notes || "Sem observações."}</p>{rows[0].history.length === 0 ? <p className="text-sm text-muted-foreground">Nenhum evento adicional registrado.</p> : rows[0].history.map((event) => <div key={event.id} className="border-l-2 border-primary/30 pl-4"><p className="text-sm font-medium">{event.action.replaceAll("_", " ")}</p><p className="text-sm text-muted-foreground">{event.description}</p><p className="text-xs text-muted-foreground">{formatDateTime(event.date)} · {event.responsibleUser}</p></div>)}</CardContent></Card>}
    <CreateRemunerationModal open={createOpen} onClose={() => setCreateOpen(false)} onSaved={() => { setCreateOpen(false); setFeedback({ tone: "success", message: "Remuneração criada a partir do aporte original." }); }} />
    <PaymentConfirmationModal open={payIds.length > 0} remunerationIds={payIds} onClose={() => setPayIds([])} onConfirm={pay} />
    <Modal open={reinvestId !== null} title="Escolher destino do reinvestimento" description="Nenhuma opção gera saída bancária; a escolha ficará no histórico." onClose={() => setReinvestId(null)} footer={<><Button variant="outline" onClick={() => setReinvestId(null)}>Cancelar</Button><Button variant="outline" onClick={() => reinvest("SAME_CONTRIBUTION")}>Mesmo aporte</Button><Button onClick={() => reinvest("NEW_CONTRIBUTION")}>Criar novo aporte</Button></>}><p className="text-sm text-muted-foreground">Escolha explicitamente se o valor líquido deve recompor o saldo do aporte atual ou originar um novo aporte demonstrativo.</p></Modal>
  </div>;

  function reinvest(target: "SAME_CONTRIBUTION" | "NEW_CONTRIBUTION") {
    if (reinvestId) fundingRepository.reinvestCapitalRemuneration(reinvestId, { date: "2026-07-31", owner: "Tesouraria Demo", notes: target === "SAME_CONTRIBUTION" ? "Escolha explícita: mesmo aporte." : "Escolha explícita: novo aporte.", target });
    setReinvestId(null); setFeedback({ tone: "success", message: target === "SAME_CONTRIBUTION" ? "Saldo do aporte atualizado sem saída bancária." : "Novo aporte criado sem saída bancária." });
  }
}

function CreateRemunerationModal({ open, onClose, onSaved }: { open: boolean; onClose: () => void; onSaved: () => void }) {
  const state = useFundingState(); const [contributionId, setContributionId] = useState(state.contributions[0]?.id ?? ""); const [competence, setCompetence] = useState("2026-08"); const [expectedDate, setExpectedDate] = useState("2026-08-10"); const [pjr, setPjr] = useState("0,00"); const [notes, setNotes] = useState(""); const contribution = state.contributions.find((item) => item.id === contributionId); const pjrAmount = currencyInputToCents(pjr);
  const save = () => { if (!contribution || pjrAmount === null) return; const input: CapitalRemunerationInput = { investorId: contribution.investorId, contributionId, competence, informedPjrAmount: pjrAmount, calculationBase: "ORIGINAL_CONTRIBUTION_AMOUNT", expectedDate, status: "PREVISTA", settlementMethod: "NOT_DEFINED", notes }; fundingRepository.createCapitalRemuneration(input); onSaved(); };
  return <Modal open={open} title="Nova Remuneração de Capital" description="A única base selecionável nesta etapa é o valor originalmente aportado." onClose={onClose} footer={<><Button variant="outline" onClick={onClose}>Cancelar</Button><Button disabled={!contribution || pjrAmount === null} onClick={save}>Criar evento</Button></>}><div className="grid gap-4 sm:grid-cols-2"><FormField label="Aporte" className="sm:col-span-2"><Select value={contributionId} onChange={(event) => setContributionId(event.target.value)}>{state.contributions.map((item) => <option key={item.id} value={item.id}>{item.code} · {formatCentsAmount(item.originalAmount)} · {item.monthlyRateBps} bps</option>)}</Select></FormField><FormField label="Competência"><Input type="month" value={competence} onChange={(event) => setCompetence(event.target.value)} /></FormField><FormField label="Data prevista"><Input type="date" value={expectedDate} onChange={(event) => setExpectedDate(event.target.value)} /></FormField><FormField label="Base"><Input value="Valor originalmente aportado" disabled /></FormField><FormField label="PJR informado"><Input value={pjr} onChange={(event) => setPjr(event.target.value)} /></FormField><FormField label="Observações" className="sm:col-span-2"><Textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></FormField></div></Modal>;
}
