import { ArrowLeft, Banknote, CalendarDays, CircleDollarSign, Percent } from "lucide-react";
import { AppLink } from "@/components/app/AppLink";
import { EmptyState } from "@/components/common/DataStates";
import { KpiCard } from "@/components/common/KpiCard";
import { PageHeader } from "@/components/common/PageHeader";
import { StatusBadge } from "@/components/common/StatusBadge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { formatCentsAmount, formatDate, formatDateTime } from "@/lib/formatters";
import { fundingRepository, useFundingState } from "@/services/fundingService";

export function ContributionDetailPage({ id, navigate }: { id: string; navigate: (path: string) => void }) {
  const state = useFundingState(); const item = state.contributions.find((value) => value.id === id); if (!item) return <EmptyState title="Aporte não encontrado" />;
  const investor = state.investors.find((value) => value.id === item.investorId); const remunerations = state.capitalRemunerationEvents.filter((value) => value.contributionId === id); const movements = state.treasuryEntries.filter((value) => value.contributionId === id); const history = state.auditEvents.filter((value) => value.entityId === id);
  return <div className="space-y-6"><AppLink to="/cadastro/aportes" onNavigate={navigate} className="inline-flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft className="size-4" />Voltar</AppLink><PageHeader eyebrow="Detalhe do aporte" title={item.code} description={`Capital demonstrativo de ${investor?.name ?? "investidor não encontrado"}.`} actions={<><StatusBadge status={item.status} />{item.status !== "CANCELADO" && !item.status.includes("LIQUIDADO") && <Button variant="outline" onClick={() => fundingRepository.setContributionStatus(id, "LIQUIDADO")}><Banknote className="size-4" />Liquidar</Button>}</>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiCard compact icon={CircleDollarSign} label="Valor original" value={formatCentsAmount(item.originalAmount)} /><KpiCard compact icon={Banknote} label="Saldo disponível" value={formatCentsAmount(item.availableBalance)} /><KpiCard compact icon={Percent} label="Taxa mensal" value={`${item.monthlyRateBps} bps`} /><KpiCard compact icon={CalendarDays} label="Remuneração mensal" value={formatCentsAmount(item.expectedMonthlyRemuneration)} helper="Base: valor originalmente aportado" /></div>
    <Card className="overflow-hidden bg-card/75"><CardHeader><CardTitle className="text-base">Remunerações de capital</CardTitle></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Competência</TableHead><TableHead>Data prevista</TableHead><TableHead>Bruto</TableHead><TableHead>PJR informado</TableHead><TableHead>Líquido</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{remunerations.map((event) => <TableRow key={event.id}><TableCell>{event.competence}</TableCell><TableCell>{formatDate(event.expectedDate)}</TableCell><TableCell>{formatCentsAmount(event.grossAmount)}</TableCell><TableCell>{formatCentsAmount(event.informedPjrAmount)}</TableCell><TableCell>{formatCentsAmount(event.netAmount)}</TableCell><TableCell><StatusBadge status={event.status} /></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
    <div className="grid gap-5 xl:grid-cols-2"><Card className="bg-card/75"><CardHeader><CardTitle className="text-base">Movimentações</CardTitle></CardHeader><CardContent className="space-y-3">{movements.map((entry) => <div key={entry.id} className="flex justify-between border-b pb-2 text-sm"><span>{formatDate(entry.date)} · {entry.type.replaceAll("_", " ")}</span><strong>{formatCentsAmount(entry.amount)}</strong></div>)}</CardContent></Card><Card className="bg-card/75"><CardHeader><CardTitle className="text-base">Histórico</CardTitle></CardHeader><CardContent className="space-y-3">{history.map((event) => <div key={event.id}><p className="text-sm">{event.description}</p><p className="text-xs text-muted-foreground">{formatDateTime(event.date)}</p></div>)}</CardContent></Card></div>
  </div>;
}
