import { AlertTriangle, Banknote, CalendarClock, CircleDollarSign, Landmark, Users } from "lucide-react";
import { ChartCard } from "@/components/charts/FundingCharts";
import { KpiCard } from "@/components/common/KpiCard";
import { PageHeader } from "@/components/common/PageHeader";
import { StatusBadge } from "@/components/common/StatusBadge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { formatCentsAmount, formatDate, formatDateTime } from "@/lib/formatters";
import { getTreasurySummary, useFundingState } from "@/services/fundingService";

export function DashboardPage() {
  const state = useFundingState(); const summary = getTreasurySummary(); const investorData = state.investors.map((investor) => ({ label: investor.code.replace("INV-DEMO-", "INV "), value: state.contributions.filter((item) => item.investorId === investor.id && item.status !== "CANCELADO").length })); const contractData = ["RELEASED", "FUNDED", "FUNDING_DIVERGENT"].map((status) => ({ label: status.replaceAll("_", " "), value: state.fundingContracts.filter((item) => item.status === status).length })); const upcoming = state.capitalRemunerationEvents.filter((item) => ["PREVISTA", "A_VENCER", "VENCE_HOJE", "ATRASADA"].includes(item.status)).sort((a, b) => a.expectedDate.localeCompare(b.expectedDate)).slice(0, 4);
  const openDivergences = [...state.fundingDivergences, ...state.treasuryDivergences].filter((item) => ["OPEN", "IN_REVIEW"].includes(item.status)).length;
  return <div className="space-y-6"><PageHeader eyebrow="Visão executiva" title="Dashboard de funding" description="Resumo separado entre contratos, entradas esperadas, tesouraria e remunerações demonstrativas." /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><KpiCard icon={CircleDollarSign} label="Principal administrado" value={formatCentsAmount(summary.principalManaged)} /><KpiCard icon={Banknote} label="Capital disponível" value={formatCentsAmount(summary.availableBalance)} /><KpiCard icon={Landmark} label="Capital alocado" value={formatCentsAmount(summary.allocatedCapital)} /><KpiCard icon={CalendarClock} label="Remuneração pendente" value={formatCentsAmount(summary.pendingPayments)} /><KpiCard icon={AlertTriangle} label="Divergências abertas" value={String(openDivergences)} /><KpiCard icon={Users} label="Investidores ativos" value={String(state.investors.filter((item) => item.status === "ATIVO").length)} /></div><div className="grid gap-5 xl:grid-cols-2"><ChartCard title="Aportes por investidor" description="Quantidade de aportes simultâneos" data={investorData} variant="bar" /><ChartCard title="Situação dos contratos" description="Operações de funding por status" data={contractData} variant="bar" /></div><div className="grid gap-5 xl:grid-cols-2"><Card className="bg-card/75"><CardHeader><CardTitle className="text-base">Próximas remunerações</CardTitle></CardHeader><CardContent className="space-y-3">{upcoming.map((item) => <div key={item.id} className="flex justify-between rounded-xl border p-4"><div><p className="text-sm font-medium">{state.investors.find((value) => value.id === item.investorId)?.name}</p><p className="text-xs text-muted-foreground">{item.competence} · {formatDate(item.expectedDate)}</p></div><div className="text-right"><p className="font-semibold">{formatCentsAmount(item.netAmount)}</p><StatusBadge status={item.status} /></div></div>)}</CardContent></Card><Card className="bg-card/75"><CardHeader><CardTitle className="text-base">Auditoria recente</CardTitle></CardHeader><CardContent className="space-y-4">{[...state.auditEvents].sort((a, b) => b.date.localeCompare(a.date)).slice(0, 7).map((event) => <div key={event.id}><p className="text-sm">{event.description}</p><p className="text-xs text-muted-foreground">{formatDateTime(event.date)} · {event.demoUser}</p></div>)}</CardContent></Card></div></div>;
}
