import { ArrowLeft, Banknote, CalendarClock, CircleDollarSign, Landmark, Pencil, Plus } from "lucide-react";
import { useState } from "react";
import { AppLink } from "@/components/app/AppLink";
import { EmptyState } from "@/components/common/DataStates";
import { KpiCard } from "@/components/common/KpiCard";
import { PageHeader } from "@/components/common/PageHeader";
import { StatusBadge } from "@/components/common/StatusBadge";
import { Tabs } from "@/components/common/Tabs";
import { ContributionFormModal } from "@/components/funding/ContributionFormModal";
import { InvestorFormModal } from "@/components/funding/InvestorFormModal";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { formatCentsAmount, formatDate, formatDateTime } from "@/lib/formatters";
import { sumCents } from "@/repositories/fundingRepository";
import { fundingRepository, useFundingState } from "@/services/fundingService";
import type { ContributionInput, InvestorInput } from "@/types/funding";

const tabs = [{ value: "overview", label: "Visão geral" }, { value: "contributions", label: "Aportes" }, { value: "revenue", label: "Receita" }, { value: "remunerations", label: "Remunerações" }, { value: "treasury", label: "Tesouraria" }, { value: "history", label: "Histórico" }];
export function InvestorDetailPage({ id, navigate }: { id: string; navigate: (path: string) => void }) {
  const state = useFundingState(); const investor = state.investors.find((item) => item.id === id); const [tab, setTab] = useState("overview"); const [edit, setEdit] = useState(false); const [contributionOpen, setContributionOpen] = useState(false); if (!investor) return <EmptyState title="Investidor não encontrado" />;
  const contributions = state.contributions.filter((item) => item.investorId === id); const remunerations = state.capitalRemunerationEvents.filter((item) => item.investorId === id); const movements = state.treasuryEntries.filter((item) => item.investorId === id); const revenueReceiptIds = new Set(state.allocationReceiptShares.filter((item) => item.investorId === id && item.status !== "REVERSED").map((item) => item.incomingReceiptId)); const revenueReceipts = state.treasuryIncomingReceipts.filter((item) => revenueReceiptIds.has(item.id)); const history = state.auditEvents.filter((item) => item.entityId === id || contributions.some((value) => value.id === item.entityId) || remunerations.some((value) => value.id === item.entityId)); const active = contributions.filter((item) => item.status !== "CANCELADO"); const next = remunerations.filter((item) => ["PREVISTA", "A_VENCER", "VENCE_HOJE", "ATRASADA"].includes(item.status)).sort((a, b) => a.expectedDate.localeCompare(b.expectedDate))[0];
  return <div className="space-y-6"><AppLink to="/cadastro/investidores" onNavigate={navigate} className="inline-flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft className="size-4" />Voltar</AppLink><PageHeader eyebrow={investor.code} title={investor.name} description={`${investor.personType} · ${investor.maskedDocument}`} actions={<><StatusBadge status={investor.status} /><Button variant="outline" onClick={() => setEdit(true)}><Pencil className="size-4" />Editar</Button><Button onClick={() => setContributionOpen(true)}><Plus className="size-4" />Novo aporte</Button></>} /><Tabs items={tabs} value={tab} onChange={setTab} />
    {tab === "overview" && <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiCard compact icon={CircleDollarSign} label="Capital aportado" value={formatCentsAmount(sumCents(active.map((item) => item.originalAmount)))} /><KpiCard compact icon={Banknote} label="Disponível" value={formatCentsAmount(sumCents(active.map((item) => item.availableBalance)))} /><KpiCard compact icon={Landmark} label="Alocado" value={formatCentsAmount(sumCents(active.map((item) => item.allocatedBalance)))} /><KpiCard compact icon={CalendarClock} label="Próxima remuneração" value={next ? formatCentsAmount(next.netAmount) : "—"} helper={next ? formatDate(next.expectedDate) : "Sem previsão"} /></div>}
    {tab === "contributions" && <DataTable><Table><TableHeader><TableRow><TableHead>Aporte</TableHead><TableHead>Status</TableHead><TableHead>Original</TableHead><TableHead>Disponível</TableHead><TableHead>Taxa</TableHead></TableRow></TableHeader><TableBody>{contributions.map((item) => <TableRow key={item.id}><TableCell><AppLink to={`/cadastro/aportes/${item.id}`} onNavigate={navigate}>{item.code}</AppLink></TableCell><TableCell><StatusBadge status={item.status} /></TableCell><TableCell>{formatCentsAmount(item.originalAmount)}</TableCell><TableCell>{formatCentsAmount(item.availableBalance)}</TableCell><TableCell>{item.monthlyRateBps} bps</TableCell></TableRow>)}</TableBody></Table></DataTable>}
    {tab === "revenue" && <DataTable><Table><TableHeader><TableRow><TableHead>Contrato</TableHead><TableHead>Parcela</TableHead><TableHead>Pagamento</TableHead><TableHead>Principal atribuído</TableHead><TableHead>Juros atribuídos</TableHead><TableHead>Acesso</TableHead></TableRow></TableHeader><TableBody>{revenueReceipts.map((receipt) => { const shares = state.allocationReceiptShares.filter((item) => item.incomingReceiptId === receipt.id && item.investorId === id && item.status !== "REVERSED"); return <TableRow key={receipt.id}><TableCell>{receipt.contractCode}</TableCell><TableCell>{receipt.installmentNumber}/{receipt.totalInstallments}</TableCell><TableCell>{formatDate(receipt.operationalWriteOffDate)}</TableCell><TableCell>{formatCentsAmount(sumCents(shares.map((item) => item.principalShare)))}</TableCell><TableCell>{formatCentsAmount(sumCents(shares.map((item) => item.interestShare)))}</TableCell><TableCell><AppLink to={`/receita/${receipt.id}`} onNavigate={navigate} className="text-primary">Abrir Receita</AppLink></TableCell></TableRow>; })}</TableBody></Table></DataTable>}
    {tab === "remunerations" && <DataTable><Table><TableHeader><TableRow><TableHead>Competência</TableHead><TableHead>Aporte</TableHead><TableHead>Bruto</TableHead><TableHead>PJR informado</TableHead><TableHead>Líquido</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{remunerations.map((item) => <TableRow key={item.id}><TableCell>{item.competence}</TableCell><TableCell>{contributions.find((value) => value.id === item.contributionId)?.code}</TableCell><TableCell>{formatCentsAmount(item.grossAmount)}</TableCell><TableCell>{formatCentsAmount(item.informedPjrAmount)}</TableCell><TableCell>{formatCentsAmount(item.netAmount)}</TableCell><TableCell><StatusBadge status={item.status} /></TableCell></TableRow>)}</TableBody></Table></DataTable>}
    {tab === "treasury" && <DataTable><Table><TableHeader><TableRow><TableHead>Data</TableHead><TableHead>Tipo</TableHead><TableHead>Natureza</TableHead><TableHead>Valor</TableHead></TableRow></TableHeader><TableBody>{movements.map((item) => <TableRow key={item.id}><TableCell>{formatDate(item.date)}</TableCell><TableCell>{item.type.replaceAll("_", " ")}</TableCell><TableCell><StatusBadge status={item.direction} /></TableCell><TableCell>{formatCentsAmount(item.amount)}</TableCell></TableRow>)}</TableBody></Table></DataTable>}
    {tab === "history" && <Card className="bg-card/75"><CardContent className="space-y-4 p-6">{history.map((event) => <div key={event.id}><p className="text-sm">{event.description}</p><p className="text-xs text-muted-foreground">{formatDateTime(event.date)} · {event.demoUser}</p></div>)}</CardContent></Card>}
    <InvestorFormModal open={edit} investor={investor} onClose={() => setEdit(false)} onSave={(input: InvestorInput) => { fundingRepository.updateInvestor(id, input); setEdit(false); }} /><ContributionFormModal open={contributionOpen} investors={state.investors} presetInvestorId={id} onClose={() => setContributionOpen(false)} onSave={(input: ContributionInput) => { fundingRepository.createContribution(input); setContributionOpen(false); }} />
  </div>;
}
function DataTable({ children }: { children: React.ReactNode }) { return <Card className="overflow-hidden bg-card/75">{children}</Card>; }
