import { AlertTriangle, Banknote, CalendarRange, CheckCircle2, Clipboard, Download, Layers3, Percent, Printer, ReceiptText, Scale, ShieldAlert, TrendingUp, Users, WalletCards } from "lucide-react";
import { useMemo, useState, type ReactNode } from "react";

import { ChartCard } from "@/components/charts/FundingCharts";
import { FormField } from "@/components/common/FormField";
import { KpiCard } from "@/components/common/KpiCard";
import { Modal } from "@/components/common/Modal";
import { PageHeader } from "@/components/common/PageHeader";
import { StatusBadge } from "@/components/common/StatusBadge";
import { Tabs, type TabItem } from "@/components/common/Tabs";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { formatCentsAmount, formatDate } from "@/lib/formatters";
import { copyReportTable, downloadReportCsv, type ExportRow } from "@/lib/reportExport";
import {
  aggregateHarvestRows, aggregateRevenueRows, buildFundingEvolution, buildFundingReport, buildHarvestReport,
  buildInvestorCashFlowReport, buildPddReport, buildRevenueReport, DEMO_REPORT_AS_OF,
  type FundingReportRow, type HarvestReportRow, type InvestorCashFlowMonthEvent,
  type InvestorCashFlowRow, type PddReportRow, type ReportRangePreset, type RevenueReportRow,
} from "@/lib/reports";
import { cents, sumCents } from "@/repositories/fundingRepository";
import { useFundingState } from "@/services/fundingService";
import type { Cents, ChartPoint } from "@/types/funding";

export type ReportsSection = "harvest" | "revenue" | "funding" | "pdd" | "investor-flow";

const reportTabs: TabItem[] = [
  { value: "harvest", label: "Safra", path: "/relatorios/safra" },
  { value: "revenue", label: "Receita", path: "/relatorios/receita" },
  { value: "funding", label: "Funding", path: "/relatorios/funding" },
  { value: "pdd", label: "PDD", path: "/relatorios/pdd" },
  { value: "investor-flow", label: "FC Investidor(a)", path: "/relatorios/fluxo-investidor" },
];

export function ReportsPage({ section, navigate }: { section: ReportsSection; navigate: (path: string) => void }) {
  return <div className="space-y-6 print:p-0"><PageHeader eyebrow="Relatórios do funding" title="Visões gerenciais derivadas" description="Consolidações demonstrativas calculadas diretamente sobre Vendas, Receita, aportes, remunerações e Tesouraria." actions={<Badge variant="warning">Regras demonstrativas</Badge>} /><Tabs items={reportTabs} value={section} navigate={navigate} />{section === "harvest" && <HarvestReport />}{section === "revenue" && <RevenueReport />}{section === "funding" && <FundingReport />}{section === "pdd" && <PddReport />}{section === "investor-flow" && <InvestorFlowReport />}</div>;
}

function ReportActions({ name, rows }: { name: string; rows: ExportRow[] }) {
  const [copied, setCopied] = useState(false);
  return <div className="flex flex-wrap gap-2 print:hidden"><Button size="sm" variant="outline" onClick={() => downloadReportCsv(`${name}-demonstrativo.csv`, rows)}><Download className="size-4" />Exportar CSV</Button><Button size="sm" variant="outline" onClick={() => window.print()}><Printer className="size-4" />Imprimir</Button><Button size="sm" variant="outline" onClick={async () => { await copyReportTable(rows); setCopied(true); window.setTimeout(() => setCopied(false), 1800); }}><Clipboard className="size-4" />{copied ? "Copiado" : "Copiar tabela"}</Button></div>;
}

function formatBps(value: number): string {
  const bps = BigInt(value); return `${bps / 100n},${(bps % 100n).toString().padStart(2, "0")}%`;
}

function chartMoney(value: Cents): number { return Number(cents(value) / 100n); }
function chartPercent(value: number): number { return Number(BigInt(value)) / 100; }
function periodLabel(value: string): string { return value.length === 4 ? value : `${value.slice(5, 7)}/${value.slice(0, 4)}`; }
function moneyExport(value: Cents): string { return formatCentsAmount(value); }

function RangeFields({ preset, setPreset, from, setFrom, to, setTo }: { preset: ReportRangePreset; setPreset: (value: ReportRangePreset) => void; from: string; setFrom: (value: string) => void; to: string; setTo: (value: string) => void }) {
  return <><FormField label="Período"><Select value={preset} onChange={(event) => setPreset(event.target.value as ReportRangePreset)}><option value="all">Todo o demonstrativo</option><option value="last12">Últimos 12 meses</option><option value="last24">Últimos 24 meses</option><option value="custom">Personalizado</option></Select></FormField>{preset === "custom" && <><FormField label="De"><Input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></FormField><FormField label="Até"><Input type="date" value={to} onChange={(event) => setTo(event.target.value)} /></FormField></>}</>;
}

function HarvestReport() {
  const state = useFundingState(); const [granularity, setGranularity] = useState<"month" | "year">("month"); const [preset, setPreset] = useState<ReportRangePreset>("all");
  const [from, setFrom] = useState("2026-01-01"); const [to, setTo] = useState(DEMO_REPORT_AS_OF); const [sort, setSort] = useState("period-asc"); const [filter, setFilter] = useState("");
  const reportRows = useMemo(() => buildHarvestReport(state, { granularity, preset, from, to, asOf: DEMO_REPORT_AS_OF }), [from, granularity, preset, state, to]);
  const rows = useMemo(() => reportRows.filter((item) => item.period.includes(filter)).sort((left, right) => sort === "period-desc" ? right.period.localeCompare(left.period) : sort === "contracts-desc" ? right.contractCount - left.contractCount : left.period.localeCompare(right.period)), [filter, reportRows, sort]);
  const totals = aggregateHarvestRows(rows);
  const exported: ExportRow[] = rows.map((item) => ({ Período: periodLabel(item.period), Contratos: item.contractCount, "Novos contratos": item.newContractCount, "Prazo médio ponderado": item.averageTermMonths, "Taxa média ponderada": formatBps(item.weightedInterestRateBps), Principal: moneyExport(item.principal), "Valor liberado": moneyExport(item.released), IOF: moneyExport(item.iof), "Projetado total": moneyExport(item.projectedTotal), "Projetado safra": moneyExport(item.projectedHarvest), "Recebimento nominal": moneyExport(item.nominalReceipt), "Recebimento real": moneyExport(item.realReceipt), "Refin/descapitalização": moneyExport(item.refinancingDecapitalization), "A vencer": moneyExport(item.due), Vencido: moneyExport(item.overdue), Prejuízo: moneyExport(item.netLoss), Inadimplência: formatBps(item.delinquencyBps) }));
  const charts = harvestCharts(rows);
  return <ReportSection title="Relatório Safra" description="Coortes pela data de operação. Prazo e taxa são ponderados pelo principal; inadimplência usa vencido ÷ (vencido + a vencer)." actions={<ReportActions name="relatorio-safra" rows={exported} />}>
    <Card className="bg-card/75 print:hidden"><CardContent className="grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-6"><FormField label="Visão"><Select value={granularity} onChange={(event) => setGranularity(event.target.value as "month" | "year")}><option value="month">Mensal</option><option value="year">Anual</option></Select></FormField><RangeFields preset={preset} setPreset={setPreset} from={from} setFrom={setFrom} to={to} setTo={setTo} /><FormField label="Filtrar período"><Input value={filter} onChange={(event) => setFilter(event.target.value)} placeholder="2026 ou 2026-07" /></FormField><FormField label="Ordenação"><Select value={sort} onChange={(event) => setSort(event.target.value)}><option value="period-asc">Período crescente</option><option value="period-desc">Período decrescente</option><option value="contracts-desc">Mais contratos</option></Select></FormField></CardContent></Card>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><KpiCard compact icon={ReceiptText} label="Contratos" value={String(totals.contracts)} /><KpiCard compact icon={Users} label="Novos contratos" value={String(totals.newContracts)} /><KpiCard compact icon={LandmarkIcon} label="Principal" value={formatCentsAmount(totals.principal)} /><KpiCard compact icon={WalletCards} label="Valor liberado" value={formatCentsAmount(totals.released)} /><KpiCard compact icon={Banknote} label="Recebido real" value={formatCentsAmount(totals.realReceipt)} /><KpiCard compact icon={CalendarRange} label="A vencer" value={formatCentsAmount(totals.due)} /><KpiCard compact icon={AlertTriangle} label="Vencido" value={formatCentsAmount(totals.overdue)} /><KpiCard compact icon={ShieldAlert} label="Prejuízo" value={formatCentsAmount(totals.netLoss)} /><KpiCard compact icon={Percent} label="Inadimplência" value={formatBps(totals.delinquencyBps)} /></div>
    <div className="grid gap-5 xl:grid-cols-2"><ChartCard title="Evolução da safra" description="Principal por período de originação." data={charts.evolution} /><ChartCard title="Projetado x recebido" description="Projetado da safra e caixa efetivamente confirmado." data={charts.projected} primaryLabel="Projetado" secondaryLabel="Recebido real" /><ChartCard title="Principal x valor liberado" description="Comparação monetária por safra." data={charts.principal} variant="area" primaryLabel="Principal" secondaryLabel="Liberado" /><ChartCard title="Inadimplência por período" description="Percentual demonstrativo em cada coorte." data={charts.delinquency} variant="bar" primaryLabel="Inadimplência (%)" /><ChartCard title="Vencido x a vencer" description="Saldos pendentes classificados pela data de referência demonstrativa." data={charts.maturity} primaryLabel="Vencido" secondaryLabel="A vencer" /></div>
    <HarvestTable rows={rows} />
  </ReportSection>;
}

const LandmarkIcon = Scale;

function harvestCharts(rows: HarvestReportRow[]) {
  const labels = (item: HarvestReportRow) => periodLabel(item.period);
  return {
    evolution: rows.map((item) => ({ label: labels(item), value: chartMoney(item.principal) })),
    projected: rows.map((item) => ({ label: labels(item), value: chartMoney(item.projectedHarvest), secondaryValue: chartMoney(item.realReceipt) })),
    principal: rows.map((item) => ({ label: labels(item), value: chartMoney(item.principal), secondaryValue: chartMoney(item.released) })),
    delinquency: rows.map((item) => ({ label: labels(item), value: chartPercent(item.delinquencyBps) })),
    maturity: rows.map((item) => ({ label: labels(item), value: chartMoney(item.overdue), secondaryValue: chartMoney(item.due) })),
  };
}

function HarvestTable({ rows }: { rows: HarvestReportRow[] }) {
  return <ResponsiveReportTable headers={["Período", "Contratos / novos", "Prazo / taxa", "VP / principal", "VL / liberado", "IOF", "Projetado total / safra", "Recebido nominal / real", "Refin / descap.", "A vencer", "Vencido", "Prejuízo", "Inadimplência"]} mobile={rows.map((item) => ({ key: item.period, title: periodLabel(item.period), status: `${item.contractCount} contratos`, metrics: [["Principal", formatCentsAmount(item.principal)], ["Liberado", formatCentsAmount(item.released)], ["Recebido real", formatCentsAmount(item.realReceipt)], ["Inadimplência", formatBps(item.delinquencyBps)]] }))}>{rows.map((item) => <TableRow key={item.period}><TableCell>{periodLabel(item.period)}</TableCell><TableCell>{item.contractCount}<p className="text-xs text-muted-foreground">{item.newContractCount} novos</p></TableCell><TableCell>{item.averageTermMonths} meses<p className="text-xs text-muted-foreground">{formatBps(item.weightedInterestRateBps)} ponderada</p></TableCell><MoneyCell value={item.principal} /><MoneyCell value={item.released} /><MoneyCell value={item.iof} /><TableCell>{formatCentsAmount(item.projectedTotal)}<p className="text-xs text-muted-foreground">Safra: {formatCentsAmount(item.projectedHarvest)}</p></TableCell><TableCell>{formatCentsAmount(item.nominalReceipt)}<p className="text-xs text-muted-foreground">Real: {formatCentsAmount(item.realReceipt)}</p></TableCell><MoneyCell value={item.refinancingDecapitalization} /><MoneyCell value={item.due} /><MoneyCell value={item.overdue} /><MoneyCell value={item.netLoss} /><TableCell>{formatBps(item.delinquencyBps)}</TableCell></TableRow>)}</ResponsiveReportTable>;
}

function RevenueReport() {
  const state = useFundingState(); const [preset, setPreset] = useState<ReportRangePreset>("all"); const [from, setFrom] = useState("2026-01-01"); const [to, setTo] = useState(DEMO_REPORT_AS_OF);
  const rows = useMemo(() => buildRevenueReport(state, { preset, from, to, asOf: DEMO_REPORT_AS_OF }), [from, preset, state, to]); const totals = aggregateRevenueRows(rows);
  const exported: ExportRow[] = rows.map((item) => ({ Competência: periodLabel(item.competence), "PMT prevista": moneyExport(item.expectedPmt), Pago: moneyExport(item.paid), Principal: moneyExport(item.principal), Juros: moneyExport(item.interest), IOF: moneyExport(item.iof), Multa: moneyExport(item.penalty), Desconto: moneyExport(item.discount), Prejuízo: moneyExport(item.loss), "Total apurado": moneyExport(item.apurated), "Recebido nominal": moneyExport(item.nominalReceived), "Recebido real": moneyExport(item.realReceived), "A vencer": moneyExport(item.due), Vencido: moneyExport(item.overdue), Parcelas: item.installmentCount, Validadas: item.validatedCount, Divergentes: item.divergentCount }));
  const points = (primary: keyof RevenueReportRow, secondary?: keyof RevenueReportRow): ChartPoint[] => rows.map((item) => ({ label: periodLabel(item.competence), value: chartMoney(item[primary] as Cents), secondaryValue: secondary ? chartMoney(item[secondary] as Cents) : undefined }));
  return <ReportSection title="Relatório Receita" description="Agregação por competência dos mesmos identificadores de recebimento exibidos no módulo Receita; nenhum registro é copiado." actions={<ReportActions name="relatorio-receita" rows={exported} />}>
    <Card className="bg-card/75 print:hidden"><CardContent className="grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-5"><RangeFields preset={preset} setPreset={setPreset} from={from} setFrom={setFrom} to={to} setTo={setTo} /></CardContent></Card>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiCard compact icon={ReceiptText} label="PMT prevista" value={formatCentsAmount(totals.expected)} /><KpiCard compact icon={Banknote} label="Recebido real" value={formatCentsAmount(totals.realReceived)} /><KpiCard compact icon={Scale} label="Principal" value={formatCentsAmount(totals.principal)} /><KpiCard compact icon={TrendingUp} label="Juros" value={formatCentsAmount(totals.interest)} /><KpiCard compact icon={CalendarRange} label="A vencer" value={formatCentsAmount(totals.due)} /><KpiCard compact icon={AlertTriangle} label="Vencido" value={formatCentsAmount(totals.overdue)} /><KpiCard compact icon={ShieldAlert} label="Prejuízo" value={formatCentsAmount(totals.loss)} /><KpiCard compact icon={CheckCircle2} label="Validadas / divergentes" value={`${totals.validated} / ${totals.divergent}`} /></div>
    <div className="grid gap-5 xl:grid-cols-2"><ChartCard title="Recebido x projetado" description="PMT prevista comparada ao recebimento real confirmado." data={points("expectedPmt", "realReceived")} primaryLabel="Projetado" secondaryLabel="Recebido real" /><ChartCard title="Principal x juros" description="Composição mensal dos recebimentos." data={points("principal", "interest")} primaryLabel="Principal" secondaryLabel="Juros" /><ChartCard title="Descontos e prejuízos" description="Reduções operacionais por competência." data={points("discount", "loss")} variant="bar" primaryLabel="Descontos" /><ChartCard title="Evolução mensal" description="Valor pago operacional ao longo das competências." data={points("paid")} /></div>
    <RevenueTable rows={rows} />
  </ReportSection>;
}

function RevenueTable({ rows }: { rows: RevenueReportRow[] }) {
  return <ResponsiveReportTable headers={["Competência", "PMT prevista / pago", "Principal / juros", "IOF / multa", "Desconto / prejuízo", "Total apurado", "Nominal / real", "A vencer / vencido", "Parcelas", "Validadas", "Divergentes"]} mobile={rows.map((item) => ({ key: item.competence, title: periodLabel(item.competence), status: `${item.installmentCount} parcelas`, metrics: [["Previsto", formatCentsAmount(item.expectedPmt)], ["Recebido real", formatCentsAmount(item.realReceived)], ["Principal", formatCentsAmount(item.principal)], ["Divergentes", String(item.divergentCount)]] }))}>{rows.map((item) => <TableRow key={item.competence}><TableCell>{periodLabel(item.competence)}</TableCell><TableCell>{formatCentsAmount(item.expectedPmt)}<p className="text-xs text-muted-foreground">Pago: {formatCentsAmount(item.paid)}</p></TableCell><TableCell>{formatCentsAmount(item.principal)}<p className="text-xs text-muted-foreground">Juros: {formatCentsAmount(item.interest)}</p></TableCell><TableCell>{formatCentsAmount(item.iof)}<p className="text-xs text-muted-foreground">Multa: {formatCentsAmount(item.penalty)}</p></TableCell><TableCell>{formatCentsAmount(item.discount)}<p className="text-xs text-muted-foreground">Prejuízo: {formatCentsAmount(item.loss)}</p></TableCell><MoneyCell value={item.apurated} /><TableCell>{formatCentsAmount(item.nominalReceived)}<p className="text-xs text-muted-foreground">Real: {formatCentsAmount(item.realReceived)}</p></TableCell><TableCell>{formatCentsAmount(item.due)}<p className="text-xs text-muted-foreground">Vencido: {formatCentsAmount(item.overdue)}</p></TableCell><TableCell>{item.installmentCount}</TableCell><TableCell>{item.validatedCount}</TableCell><TableCell>{item.divergentCount}</TableCell></TableRow>)}</ResponsiveReportTable>;
}

function FundingReport() {
  const state = useFundingState(); const [investor, setInvestor] = useState(""); const [preset, setPreset] = useState<ReportRangePreset>("all"); const [from, setFrom] = useState("2026-01-01"); const [to, setTo] = useState(DEMO_REPORT_AS_OF);
  const allRows = useMemo(() => buildFundingReport(state, { preset, from, to, asOf: DEMO_REPORT_AS_OF }), [from, preset, state, to]); const rows = allRows.filter((item) => !investor || item.investorId === investor);
  const evolution = useMemo(() => buildFundingEvolution(state, { preset, from, to, asOf: DEMO_REPORT_AS_OF }), [from, preset, state, to]);
  const total = (selector: (item: FundingReportRow) => Cents) => sumCents(rows.map(selector)); const exported: ExportRow[] = rows.map((item) => ({ "Investidor/fonte": item.label, Tipo: item.kind, "Capital original": moneyExport(item.originalCapital), Disponível: moneyExport(item.availableCapital), Alocado: moneyExport(item.allocatedCapital), Contratos: item.contractCount, "Principal financiado": moneyExport(item.financedPrincipal), Liberado: moneyExport(item.released), Projetado: moneyExport(item.projected), "Principal recuperado": moneyExport(item.principalRecovered), "Juros recebidos": moneyExport(item.interestReceived), Remuneração: moneyExport(item.capitalRemuneration), Devolvido: moneyExport(item.returnedCapital), Reinvestido: moneyExport(item.reinvested), Saldo: moneyExport(item.balance), Vencido: moneyExport(item.overdue), Prejuízo: moneyExport(item.loss), Retorno: formatBps(item.returnBps), Inadimplência: formatBps(item.delinquencyBps) }));
  return <ReportSection title="Relatório Funding" description="Posição derivada por investidor e fonte. Capital próprio REMO é mantido como fonte independente, sem investidor artificial." actions={<ReportActions name="relatorio-funding" rows={exported} />}>
    <Card className="bg-card/75 print:hidden"><CardContent className="grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-5"><FormField label="Investidor"><Select value={investor} onChange={(event) => setInvestor(event.target.value)}><option value="">Investidores e fontes</option>{state.investors.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></FormField><RangeFields preset={preset} setPreset={setPreset} from={from} setFrom={setFrom} to={to} setTo={setTo} /></CardContent></Card>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiCard compact icon={WalletCards} label="Capital original" value={formatCentsAmount(total((item) => item.originalCapital))} /><KpiCard compact icon={Banknote} label="Capital disponível" value={formatCentsAmount(total((item) => item.availableCapital))} /><KpiCard compact icon={Layers3} label="Capital alocado" value={formatCentsAmount(total((item) => item.allocatedCapital))} /><KpiCard compact icon={TrendingUp} label="Juros recebidos" value={formatCentsAmount(total((item) => item.interestReceived))} /></div>
    <div className="grid gap-5 xl:grid-cols-2"><ChartCard title="Funding por investidor" description="Capital originalmente aportado por investidor ou fonte." data={rows.map((item) => ({ label: item.label, value: chartMoney(item.originalCapital) }))} variant="donut" /><ChartCard title="Capital alocado x disponível" description="Posição atual derivada dos aportes e alocações." data={rows.map((item) => ({ label: item.label, value: chartMoney(item.allocatedCapital), secondaryValue: chartMoney(item.availableCapital) }))} primaryLabel="Alocado" secondaryLabel="Disponível" /><ChartCard title="Retorno por investidor" description="Juros e remunerações sobre o capital original; métrica demonstrativa." data={rows.map((item) => ({ label: item.label, value: chartPercent(item.returnBps) }))} variant="bar" primaryLabel="Retorno (%)" /><ChartCard title="Exposição" description="Principal financiado proporcional à composição do funding." data={rows.map((item) => ({ label: item.label, value: chartMoney(item.financedPrincipal) }))} variant="bar" /><ChartCard title="Recebido por investidor" description="Principal e juros derivados dos rateios existentes." data={rows.map((item) => ({ label: item.label, value: chartMoney(item.principalRecovered), secondaryValue: chartMoney(item.interestReceived) }))} primaryLabel="Principal" secondaryLabel="Juros" /><ChartCard title="Evolução do funding" description="Capital aportado e alocado acumulados por competência." data={evolution.map((item) => ({ label: periodLabel(item.competence), value: chartMoney(item.cumulativeCapital), secondaryValue: chartMoney(item.cumulativeAllocated) }))} primaryLabel="Capital acumulado" secondaryLabel="Alocado acumulado" /></div>
    <FundingTable rows={rows} state={state} />
  </ReportSection>;
}

function FundingTable({ rows, state }: { rows: FundingReportRow[]; state: ReturnType<typeof useFundingState> }) {
  return <ResponsiveReportTable headers={["Investidor / fonte", "Capital original", "Disponível / alocado", "Contratos", "Principal / liberado", "Projetado", "Principal recuperado / juros", "Remuneração", "Devolvido / reinvestido", "Saldo", "Vencido / prejuízo", "Retorno / inadimplência", "Detalhe"]} mobile={rows.map((item) => ({ key: item.id, title: item.label, status: item.kind === "REMO_OWN_CAPITAL" ? "Capital próprio REMO" : item.kind, metrics: [["Capital original", formatCentsAmount(item.originalCapital)], ["Alocado", formatCentsAmount(item.allocatedCapital)], ["Saldo", formatCentsAmount(item.balance)], ["Retorno", formatBps(item.returnBps)]] }))}>{rows.map((item) => <TableRow key={item.id}><TableCell className="font-medium">{item.label}<p className="text-xs text-muted-foreground">{item.kind === "REMO_OWN_CAPITAL" ? "Fonte própria" : item.kind === "INVESTOR" ? "Investidor" : "Outra fonte"}</p></TableCell><MoneyCell value={item.originalCapital} /><TableCell>{formatCentsAmount(item.availableCapital)}<p className="text-xs text-muted-foreground">Alocado: {formatCentsAmount(item.allocatedCapital)}</p></TableCell><TableCell>{item.contractCount}</TableCell><TableCell>{formatCentsAmount(item.financedPrincipal)}<p className="text-xs text-muted-foreground">Liberado: {formatCentsAmount(item.released)}</p></TableCell><MoneyCell value={item.projected} /><TableCell>{formatCentsAmount(item.principalRecovered)}<p className="text-xs text-muted-foreground">Juros: {formatCentsAmount(item.interestReceived)}</p></TableCell><MoneyCell value={item.capitalRemuneration} /><TableCell>{formatCentsAmount(item.returnedCapital)}<p className="text-xs text-muted-foreground">Reinvestido: {formatCentsAmount(item.reinvested)}</p></TableCell><MoneyCell value={item.balance} /><TableCell>{formatCentsAmount(item.overdue)}<p className="text-xs text-muted-foreground">Prejuízo: {formatCentsAmount(item.loss)}</p></TableCell><TableCell>{formatBps(item.returnBps)}<p className="text-xs text-muted-foreground">Inadimplência: {formatBps(item.delinquencyBps)}</p></TableCell><TableCell><details><summary className="cursor-pointer text-primary">Abrir detalhe</summary><div className="mt-2 min-w-64 space-y-2 rounded-lg border bg-popover p-3 text-xs"><strong>Contratos relacionados</strong>{item.contractIds.length ? item.contractIds.map((id) => <p key={id}>{state.fundingContracts.find((value) => value.id === id)?.contractCode ?? id}</p>) : <p>Nenhum contrato</p>}<strong className="block pt-2">Aportes relacionados</strong>{item.contributionIds.length ? item.contributionIds.map((id) => <p key={id}>{state.contributions.find((value) => value.id === id)?.code ?? id}</p>) : <p>Não se aplica à fonte</p>}</div></details></TableCell></TableRow>)}</ResponsiveReportTable>;
}

function PddReport() {
  const state = useFundingState(); const report = useMemo(() => buildPddReport(state, { asOf: DEMO_REPORT_AS_OF }), [state]); const rows = report.rows;
  const principalFor = (ratings: string[]) => sumCents(rows.filter((item) => ratings.includes(item.rating)).map((item) => item.principal));
  const exported: ExportRow[] = rows.map((item) => ({ Rating: item.rating, Faixa: item.description, "Taxa média ponderada": formatBps(item.weightedInterestRateBps), Clientes: item.clientCount, "% clientes": formatBps(item.clientShareBps), Contratos: item.contractCount, "% contratos": formatBps(item.contractShareBps), Principal: moneyExport(item.principal), "% principal": formatBps(item.principalShareBps), Recebido: moneyExport(item.received), "% recebido": formatBps(item.receivedShareBps), Pendente: moneyExport(item.pending), "% pendente": formatBps(item.pendingShareBps), PDD: "Regra a confirmar com a REMO", "Participação PDD": "—" }));
  const riskPalette = ["#22c55e", "#84cc16", "#eab308", "#f59e0b", "#f97316", "#fb7185", "#ef4444", "#dc2626", "#991b1b"];
  return <ReportSection title="PDD — Distribuição da Carteira por Rating" description="Visão da carteira distribuída conforme faixa de atraso e situação dos contratos." actions={<ReportActions name="distribuicao-carteira-rating" rows={exported} />}>
    <div className="rounded-xl border border-amber-400/25 bg-amber-400/5 p-4 text-sm text-muted-foreground"><strong className="text-amber-400">PDD: Regra a confirmar com a REMO.</strong> Esta tela classifica a carteira por atraso; não aplica percentuais nem calcula provisão financeira.</div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><KpiCard compact icon={Users} label="Total de clientes" value={String(report.totals.clientCount)} /><KpiCard compact icon={ReceiptText} label="Total de contratos" value={String(report.totals.contractCount)} /><KpiCard compact icon={Scale} label="Principal da carteira" value={formatCentsAmount(report.totals.principal)} /><KpiCard compact icon={Banknote} label="Total recebido" value={formatCentsAmount(report.totals.received)} /><KpiCard compact icon={CalendarRange} label="Total pendente" value={formatCentsAmount(report.totals.pending)} /><KpiCard compact icon={CheckCircle2} label="Carteira A/B" value={formatCentsAmount(principalFor(["A", "B"]))} /><KpiCard compact icon={AlertTriangle} label="Carteira C–G" value={formatCentsAmount(principalFor(["C", "D", "E", "F", "G"]))} /><KpiCard compact icon={ShieldAlert} label="Carteira H" value={formatCentsAmount(principalFor(["H"]))} /><KpiCard compact icon={ShieldAlert} label="Carteira HH / prejuízo" value={formatCentsAmount(principalFor(["HH"]))} />{report.totals.pddAmount && <KpiCard compact icon={Percent} label="PDD total demonstrativa" value={formatCentsAmount(report.totals.pddAmount)} />}</div>
    <div className="grid gap-5 xl:grid-cols-2"><ChartCard title="Distribuição do principal por rating" description="Principal da carteira em cada faixa de atraso." data={rows.map((item) => ({ label: item.rating, value: chartMoney(item.principal) }))} variant="donut" palette={riskPalette} /><ChartCard title="Quantidade de contratos por rating" description="Contratos classificados em cada faixa." data={rows.map((item) => ({ label: item.rating, value: item.contractCount }))} variant="bar" palette={riskPalette} primaryLabel="Contratos" /><ChartCard title="Pendente por rating" description="Principal ainda pendente por faixa de atraso." data={rows.map((item) => ({ label: item.rating, value: chartMoney(item.pending) }))} variant="bar" palette={riskPalette} /><ChartCard title="Recebido por rating" description="Caixa confirmado associado aos contratos de cada rating." data={rows.map((item) => ({ label: item.rating, value: chartMoney(item.received) }))} variant="bar" palette={riskPalette} /><ChartCard title="Distribuição percentual da carteira" description="Participação de cada rating no principal total." data={rows.map((item) => ({ label: item.rating, value: chartPercent(item.principalShareBps) }))} variant="bar" palette={riskPalette} primaryLabel="Participação (%)" />{report.history.length > 0 ? <ChartCard title="Evolução dos ratings" description="Histórico disponível nos mocks demonstrativos." data={report.history.map((item) => ({ label: `${periodLabel(item.competence)} · ${item.rating}`, value: chartMoney(item.principal) }))} palette={riskPalette} /> : <Card className="bg-card/75"><CardHeader><CardTitle className="text-base">Evolução dos ratings</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">Os mocks atuais não possuem histórico de rating. O gráfico será exibido quando eventos históricos estiverem disponíveis.</CardContent></Card>}</div>
    <PddTable rows={rows} totals={report.totals} />
  </ReportSection>;
}

function PddTable({ rows, totals }: { rows: PddReportRow[]; totals: ReturnType<typeof buildPddReport>["totals"] }) {
  const has = (value: Cents | number) => typeof value === "number" ? value > 0 : cents(value) > 0n;
  const mobile = rows.map((item) => ({ key: item.rating, title: `Rating ${item.rating} · ${item.description}`, status: `${item.contractCount} contratos`, metrics: [["Principal", formatCentsAmount(item.principal)], ["Recebido", formatCentsAmount(item.received)], ["Pendente", formatCentsAmount(item.pending)], ["Participação", formatBps(item.principalShareBps)]] as [string, string][] }));
  return <><Card className="hidden overflow-hidden bg-card/75 md:block"><Table className="min-w-[2100px]"><TableHeader className="sticky top-0 z-10 bg-card"><TableRow>{["Rating", "Faixa de atraso", "Taxa média", "Clientes", "% clientes", "Contratos", "% contratos", "Principal", "% principal", "Recebido", "% recebido", "Pendente", "% pendente", "PDD", "Participação PDD"].map((item) => <TableHead key={item} className="whitespace-nowrap">{item}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((item) => <TableRow key={item.rating}><TableCell><RatingBadge rating={item.rating} /></TableCell><TableCell>{item.description}</TableCell><TableCell>{formatBps(item.weightedInterestRateBps)}</TableCell><TableCell>{item.clientCount}</TableCell><TableCell>{formatBps(item.clientShareBps)}</TableCell><TableCell>{item.contractCount}</TableCell><TableCell>{formatBps(item.contractShareBps)}</TableCell><MoneyCell value={item.principal} /><TableCell>{formatBps(item.principalShareBps)}</TableCell><MoneyCell value={item.received} /><TableCell>{formatBps(item.receivedShareBps)}</TableCell><MoneyCell value={item.pending} /><TableCell>{formatBps(item.pendingShareBps)}</TableCell><TableCell className="text-amber-400">Regra a confirmar com a REMO</TableCell><TableCell>—</TableCell></TableRow>)}<TableRow className="bg-muted/40 font-semibold"><TableCell>TOTAL</TableCell><TableCell>Carteira demonstrativa</TableCell><TableCell>{formatBps(totals.weightedInterestRateBps)}</TableCell><TableCell>{totals.clientCount}</TableCell><TableCell>{has(totals.clientCount) ? "100,00%" : "0,00%"}</TableCell><TableCell>{totals.contractCount}</TableCell><TableCell>{has(totals.contractCount) ? "100,00%" : "0,00%"}</TableCell><MoneyCell value={totals.principal} /><TableCell>{has(totals.principal) ? "100,00%" : "0,00%"}</TableCell><MoneyCell value={totals.received} /><TableCell>{has(totals.received) ? "100,00%" : "0,00%"}</TableCell><MoneyCell value={totals.pending} /><TableCell>{has(totals.pending) ? "100,00%" : "0,00%"}</TableCell><TableCell className="text-amber-400">Regra a confirmar</TableCell><TableCell>—</TableCell></TableRow></TableBody></Table></Card><div className="grid gap-3 md:hidden">{mobile.map((item) => <Card key={item.key} className="bg-card/75"><CardContent className="p-4"><div className="flex items-start justify-between gap-3"><strong>{item.title}</strong><span className="text-xs text-muted-foreground">{item.status}</span></div><div className="mt-4 grid grid-cols-2 gap-3">{item.metrics.map(([label, value]) => <div key={label}><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-sm font-medium">{value}</p></div>)}</div></CardContent></Card>)}</div></>;
}

function RatingBadge({ rating }: { rating: PddReportRow["rating"] }) { const variant = ["A", "B"].includes(rating) ? "success" : ["C", "D", "E", "F", "G"].includes(rating) ? "warning" : "danger"; return <Badge variant={variant}>{rating}</Badge>; }

function InvestorFlowReport() {
  const state = useFundingState(); const [investorId, setInvestorId] = useState(state.investors[0]?.id ?? ""); const [contributionId, setContributionId] = useState("");
  const [preset, setPreset] = useState<ReportRangePreset>("last12"); const [from, setFrom] = useState("2026-01-01"); const [to, setTo] = useState(DEMO_REPORT_AS_OF);
  const [view, setView] = useState("grid"); const [selectedCompetence, setSelectedCompetence] = useState<string | null>(null);
  const report = useMemo(() => investorId ? buildInvestorCashFlowReport(state, investorId, { contributionId: contributionId || undefined, preset, from, to, asOf: DEMO_REPORT_AS_OF }) : null, [contributionId, from, investorId, preset, state, to]);
  const investor = state.investors.find((item) => item.id === investorId); const contributions = state.contributions.filter((item) => item.investorId === investorId); const selectedMonth = report?.rows.find((item) => item.competence === selectedCompetence);
  if (!report) return <Card><CardContent className="p-6 text-sm text-muted-foreground">Nenhum investidor demonstrativo disponível.</CardContent></Card>;
  const totalContributed = sumCents([report.originalContribution, report.additionalContributions]);
  const exported: ExportRow[] = report.rows.map((item) => ({ Competência: periodLabel(item.competence), "% utilização": formatBps(item.utilizationBps), Empréstimos: moneyExport(item.allocations), "Principal recebido": moneyExport(item.principalReceived), "Juros recebidos": moneyExport(item.interestReceived), ROC: "Regra de ROC a confirmar com a REMO", "Remuneração de Capital": moneyExport(item.remuneration), Reinvestimentos: moneyExport(item.reinvestments), "Devoluções de capital": moneyExport(item.returns), Ajustes: moneyExport(item.adjustments), "Saldo final": moneyExport(item.closingBalance) }));
  return <ReportSection title="FC Investidor(a) — Fluxo Financeiro Mensal" description="Evolução histórica do saldo disponível, capital alocado e movimentos mensais do investidor selecionado." actions={<ReportActions name="fluxo-financeiro-investidor" rows={exported} />}>
    <Card className="bg-card/75 print:hidden"><CardContent className="grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-5"><FormField label="Investidor"><Select value={investorId} onChange={(event) => { setInvestorId(event.target.value); setContributionId(""); setSelectedCompetence(null); }} >{state.investors.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></FormField><FormField label="Aporte"><Select value={contributionId} onChange={(event) => setContributionId(event.target.value)}><option value="">Todos os aportes</option>{contributions.map((item) => <option key={item.id} value={item.id}>{item.code}</option>)}</Select></FormField><FormField label="Período"><Select value={preset} onChange={(event) => setPreset(event.target.value as ReportRangePreset)}><option value="last6">Últimos 6 meses</option><option value="last12">Últimos 12 meses</option><option value="last24">Últimos 24 meses</option><option value="custom">Personalizado</option></Select></FormField>{preset === "custom" && <><FormField label="De"><Input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></FormField><FormField label="Até"><Input type="date" value={to} onChange={(event) => setTo(event.target.value)} /></FormField></>}</CardContent></Card>
    <Card className="bg-card/75"><CardContent className="grid gap-4 p-6 sm:grid-cols-2 xl:grid-cols-4"><PositionItem label="Investidor" value={investor?.name ?? "—"} helper={`${report.investorCode} · ${investor?.maskedDocument ?? ""}`} /><PositionItem label="Capital originalmente aportado" value={formatCentsAmount(totalContributed)} /><PositionItem label="Data inicial" value={formatDate(report.initialDate)} /><PositionItem label="Aportes adicionais" value={formatCentsAmount(report.additionalContributions)} /><PositionItem label="Capital atual" value={formatCentsAmount(report.currentCapital)} /><PositionItem label="Capital alocado" value={formatCentsAmount(report.allocatedCapital)} /><PositionItem label="Saldo disponível" value={formatCentsAmount(report.availableCapital)} /><PositionItem label="Principal recuperado" value={formatCentsAmount(report.principalReceived)} /><PositionItem label="Juros recebidos" value={formatCentsAmount(report.interestReceived)} /><PositionItem label="Remuneração de Capital paga" value={formatCentsAmount(report.paidRemuneration)} /><PositionItem label="Percentual atualmente utilizado" value={formatBps(report.currentUtilizationBps)} /><PositionItem label="Privacidade" value="Dados bancários não exibidos" /></CardContent></Card>
    <Tabs items={[{ value: "grid", label: "Grade mensal" }, { value: "charts", label: "Gráficos" }]} value={view} onChange={setView} />
    {view === "grid" && <InvestorMonthlyGrid rows={report.rows} onSelect={setSelectedCompetence} />}
    {view === "charts" && <InvestorFlowCharts rows={report.rows} />}
    <div className="grid gap-4 xl:grid-cols-2"><RelatedCard title="Aportes considerados">{report.contributionIds.map((id) => { const item = state.contributions.find((value) => value.id === id); return <RelatedRow key={id} title={item?.code ?? id} value={item ? formatCentsAmount(item.originalAmount) : "—"} />; })}</RelatedCard><RelatedCard title="Contratos financiados">{report.contractIds.map((id) => { const item = state.fundingContracts.find((value) => value.id === id); return <RelatedRow key={id} title={item?.contractCode ?? id} value={item ? formatCentsAmount(item.releasedAmount) : "—"} />; })}</RelatedCard><RelatedCard title="Remunerações de Capital">{report.remunerationIds.map((id) => { const item = state.capitalRemunerationEvents.find((value) => value.id === id); return <RelatedRow key={id} title={item?.competence ?? id} value={item ? formatCentsAmount(item.netAmount) : "—"} status={item?.status} />; })}</RelatedCard><RelatedCard title="Movimentos relacionados">{report.treasuryEntryIds.map((id) => { const item = state.treasuryEntries.find((value) => value.id === id); return <RelatedRow key={id} title={item?.reference ?? id} value={item ? formatCentsAmount(item.amount) : "—"} status={item?.status} />; })}</RelatedCard></div>
    <InvestorMonthModal row={selectedMonth} onClose={() => setSelectedCompetence(null)} />
  </ReportSection>;
}

function PositionItem({ label, value, helper }: { label: string; value: string; helper?: string }) { return <div><p className="text-xs uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-1 font-semibold">{value}</p>{helper && <p className="mt-1 text-xs text-muted-foreground">{helper}</p>}</div>; }

function InvestorMonthlyGrid({ rows, onSelect }: { rows: InvestorCashFlowRow[]; onSelect: (competence: string) => void }) {
  const metrics: Array<{ label: string; value: (row: InvestorCashFlowRow) => ReactNode; help?: string }> = [
    { label: "% utilização", value: (row) => formatBps(row.utilizationBps) }, { label: "Empréstimos", value: (row) => formatCentsAmount(row.allocations) },
    { label: "Principal recebido", value: (row) => formatCentsAmount(row.principalReceived) }, { label: "Juros recebidos", value: (row) => formatCentsAmount(row.interestReceived) },
    { label: "ROC", help: "Regra de ROC a confirmar com a REMO.", value: () => <span className="text-amber-400">A confirmar</span> },
    { label: "Remuneração de Capital", value: (row) => formatCentsAmount(row.remuneration) }, { label: "Reinvestimentos", value: (row) => formatCentsAmount(row.reinvestments) },
    { label: "Devoluções de capital", value: (row) => formatCentsAmount(row.returns) }, { label: "Saldo final", value: (row) => formatCentsAmount(row.closingBalance) },
  ];
  return <><Card className="hidden overflow-hidden bg-card/75 md:block"><Table className="min-w-max"><TableHeader><TableRow><TableHead className="sticky left-0 z-20 min-w-56 bg-card">Métrica</TableHead>{rows.map((row) => <TableHead key={row.competence} className="min-w-40 text-center"><button className="text-primary hover:underline" onClick={() => onSelect(row.competence)}>{periodLabel(row.competence)}</button></TableHead>)}</TableRow></TableHeader><TableBody>{metrics.map((metric) => <TableRow key={metric.label}><TableCell className="sticky left-0 z-10 bg-card font-medium" title={metric.help}>{metric.label}{metric.help && <span className="ml-1 text-amber-400">ⓘ</span>}</TableCell>{rows.map((row) => <TableCell key={row.competence} className="text-center">{metric.value(row)}</TableCell>)}</TableRow>)}</TableBody></Table></Card><div className="grid gap-3 md:hidden">{rows.map((row) => <button key={row.competence} className="rounded-lg border bg-card/75 p-4 text-left" onClick={() => onSelect(row.competence)}><div className="flex justify-between gap-3"><strong>{periodLabel(row.competence)}</strong><span className="text-sm text-primary">Ver detalhe</span></div><div className="mt-4 grid grid-cols-2 gap-3"><PositionItem label="Empréstimos" value={formatCentsAmount(row.allocations)} /><PositionItem label="Principal recebido" value={formatCentsAmount(row.principalReceived)} /><PositionItem label="Remuneração de Capital" value={formatCentsAmount(row.remuneration)} /><PositionItem label="Saldo final" value={formatCentsAmount(row.closingBalance)} /></div></button>)}</div></>;
}

function InvestorFlowCharts({ rows }: { rows: InvestorCashFlowRow[] }) { const moneyPoints = (selector: (row: InvestorCashFlowRow) => Cents) => rows.map((row) => ({ label: periodLabel(row.competence), value: chartMoney(selector(row)) })); return <div className="grid gap-5 xl:grid-cols-2"><ChartCard title="Evolução do saldo" description="Saldo disponível ao final de cada competência." data={moneyPoints((row) => row.closingBalance)} /><ChartCard title="Capital alocado" description="Saldo de principal alocado historicamente." data={moneyPoints((row) => row.allocatedBalance)} /><ChartCard title="Novos empréstimos por mês" description="Novas alocações/liberações da composição de funding." data={moneyPoints((row) => row.allocations)} variant="bar" /><ChartCard title="Principal recuperado" description="Principal retornado pelos rateios da Receita." data={moneyPoints((row) => row.principalReceived)} variant="bar" /><ChartCard title="Juros recebidos" description="Juros mantidos separados do saldo principal." data={moneyPoints((row) => row.interestReceived)} variant="bar" /><ChartCard title="Remuneração de Capital" description="Pagamentos mensais derivados das remunerações existentes." data={moneyPoints((row) => row.remuneration)} variant="bar" /><ChartCard title="Utilização percentual do capital" description="Capital alocado ÷ capital total da posição em cada competência." data={rows.map((row) => ({ label: periodLabel(row.competence), value: chartPercent(row.utilizationBps) }))} primaryLabel="Utilização (%)" /></div>; }

function InvestorMonthModal({ row, onClose }: { row?: InvestorCashFlowRow; onClose: () => void }) { return <Modal open={Boolean(row)} title={row ? `Detalhe de ${periodLabel(row.competence)}` : "Detalhe mensal"} description="Eventos demonstrativos que formam o saldo histórico da competência." onClose={onClose} footer={<Button onClick={onClose}>Fechar</Button>}>{row && <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2"><PositionItem label="Saldo inicial" value={formatCentsAmount(row.openingBalance)} /><PositionItem label="Novos aportes" value={formatCentsAmount(row.contributions)} /><PositionItem label="Ajustes / reintegrações" value={formatCentsAmount(row.adjustments)} /><PositionItem label="Saldo final" value={formatCentsAmount(row.closingBalance)} /></div><MonthEvents title="Contratos financiados" events={row.detail.fundedContracts} /><MonthEvents title="Principal recuperado" events={row.detail.principalReceipts} /><MonthEvents title="Juros recebidos" events={row.detail.interestReceipts} /><MonthEvents title="Remuneração de Capital" events={row.detail.remunerations} /><MonthEvents title="Reinvestimentos" events={row.detail.reinvestments} /><MonthEvents title="Devoluções" events={row.detail.returns} /><MonthEvents title="Ajustes" events={row.detail.adjustments} /><div className="rounded-lg border border-amber-400/20 bg-amber-400/5 p-3 text-sm text-amber-400" title="Regra de ROC a confirmar com a REMO.">ROC — Regra de ROC a confirmar com a REMO.</div></div>}</Modal>; }
function MonthEvents({ title, events }: { title: string; events: InvestorCashFlowMonthEvent[] }) { return <div><p className="mb-2 text-sm font-semibold">{title}</p>{events.length ? <div className="space-y-2">{events.map((event) => <div key={event.id} className="flex justify-between gap-3 rounded-lg border p-3 text-sm"><span>{event.label}</span><strong>{formatCentsAmount(event.amount)}</strong></div>)}</div> : <p className="text-sm text-muted-foreground">Nenhum evento nesta competência.</p>}</div>; }

function ReportSection({ title, description, actions, children }: { title: string; description: string; actions: ReactNode; children: ReactNode }) { return <section className="space-y-6"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><h2 className="text-xl font-semibold">{title}</h2><p className="mt-1 max-w-4xl text-sm text-muted-foreground">{description}</p></div>{actions}</div>{children}</section>; }

type MobileRecord = { key: string; title: string; status: string; metrics: [string, string][] };
function ResponsiveReportTable({ headers, mobile, children }: { headers: string[]; mobile: MobileRecord[]; children: ReactNode }) { return <><Card className="hidden overflow-hidden bg-card/75 md:block"><Table className="min-w-[1500px]"><TableHeader className="sticky top-0 z-10 bg-card"><TableRow>{headers.map((item) => <TableHead key={item} className="whitespace-nowrap">{item}</TableHead>)}</TableRow></TableHeader><TableBody>{children}</TableBody></Table></Card><div className="grid gap-3 md:hidden">{mobile.map((item) => <Card key={item.key} className="bg-card/75"><CardContent className="p-4"><div className="flex items-start justify-between gap-3"><strong>{item.title}</strong><span className="text-xs text-muted-foreground">{item.status}</span></div><div className="mt-4 grid grid-cols-2 gap-3">{item.metrics.map(([label, value]) => <div key={label}><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-sm font-medium">{value}</p></div>)}</div></CardContent></Card>)}</div></>; }
function MoneyCell({ value }: { value: Cents }) { return <TableCell>{formatCentsAmount(value)}</TableCell>; }
function RelatedCard({ title, children }: { title: string; children: ReactNode }) { return <Card className="bg-card/75"><CardHeader><CardTitle className="text-base">{title}</CardTitle></CardHeader><CardContent className="space-y-2">{children}</CardContent></Card>; }
function RelatedRow({ title, value, status }: { title: string; value: string; status?: string }) { return <div className="flex items-center justify-between gap-3 rounded-lg border p-3 text-sm"><div><strong>{title}</strong>{status && <div className="mt-1"><StatusBadge status={status} /></div>}</div><span>{value}</span></div>; }
