import { AlertTriangle, ArrowLeft, Banknote, CheckCircle2, RefreshCcw, Scale, ShieldCheck } from "lucide-react";
import { useState } from "react";

import { AppLink } from "@/components/app/AppLink";
import { EmptyState } from "@/components/common/DataStates";
import { FeedbackBanner, type Feedback } from "@/components/common/FeedbackBanner";
import { FormField } from "@/components/common/FormField";
import { KpiCard } from "@/components/common/KpiCard";
import { Modal } from "@/components/common/Modal";
import { PageHeader } from "@/components/common/PageHeader";
import { StatusBadge } from "@/components/common/StatusBadge";
import { Tabs } from "@/components/common/Tabs";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { revenueDivergenceLabels } from "@/data/revenueOptions";
import { currencyInputToCents, formatCentsAmount, formatDate, formatDateTime } from "@/lib/formatters";
import { cents, sumCents } from "@/repositories/fundingRepository";
import { fundingRepository, useFundingState, useRevenueRecords } from "@/services/fundingService";

const tabs = [
  { value: "summary", label: "Resumo" }, { value: "components", label: "Composição da parcela" },
  { value: "bank", label: "Validação bancária" }, { value: "allocation", label: "Rateio do recebimento" },
  { value: "treasury", label: "Movimentos de tesouraria" }, { value: "divergences", label: "Divergências" },
  { value: "source", label: "Fonte operacional" }, { value: "history", label: "Histórico" },
];

export function RevenueDetailPage({ id, navigate }: { id: string; navigate: (path: string) => void }) {
  const state = useFundingState(); const record = useRevenueRecords().find((item) => item.id === id); const receipt = state.treasuryIncomingReceipts.find((item) => item.id === id);
  const [tab, setTab] = useState("summary"); const [feedback, setFeedback] = useState<Feedback | null>(null); const [adjustmentOpen, setAdjustmentOpen] = useState(false);
  if (!record || !receipt) return <EmptyState title="Recebimento de Receita não encontrado" />;
  const links = state.receiptBankReconciliations.filter((item) => item.incomingReceiptId === id);
  const bankMovements = links.flatMap((link) => { const movement = state.bankMovements.find((item) => item.id === link.bankMovementId); return movement ? [{ link, movement }] : []; });
  const bankIds = new Set(bankMovements.map((item) => item.movement.id));
  const treasury = state.treasuryEntries.filter((item) => item.incomingReceiptId === id || (item.bankMovementId && bankIds.has(item.bankMovementId)));
  const shares = state.allocationReceiptShares.filter((item) => item.incomingReceiptId === id);
  const divergences = state.revenueDivergences.filter((item) => item.incomingReceiptId === id);
  const relatedIds = new Set([id, ...bankMovements.map((item) => item.movement.id), ...divergences.map((item) => item.id)]);
  const history = state.auditEvents.filter((item) => relatedIds.has(item.entityId));
  const reconciled = sumCents(links.filter((item) => item.status === "ACTIVE").map((item) => item.amount));
  const reverse = () => {
    const movement = bankMovements.find((item) => item.movement.status === "FOUND")?.movement;
    if (!movement) return;
    fundingRepository.reverseBankMovement(movement.id, { date: "2026-08-04", owner: "Receita Demo", notes: "Estorno iniciado pelo detalhe da Receita." });
    setFeedback({ tone: "success", message: "Recebimento estornado com caixa, vínculos, rateio e histórico preservados." });
  };
  return <div className="space-y-6">
    <AppLink to="/receita" onNavigate={navigate} className="inline-flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft className="size-4" />Voltar para Receita</AppLink>
    <PageHeader eyebrow={`${record.contractCode} · parcela ${record.installmentNumber}/${record.totalInstallments}`} title={record.maskedClientName} description={`Identificador central ${record.id}: a Receita e a Tesouraria referenciam exatamente o mesmo recebimento.`} actions={<><StatusBadge status={record.revenueStatus} /><Button variant="outline" onClick={() => navigate(`/tesouraria/entradas/${id}`)}><ShieldCheck className="size-4" />Abrir validação bancária</Button><Button variant="outline" disabled={record.bankValidationStatus !== "VALIDATED"} onClick={() => { fundingRepository.recalculateRevenueAllocation(id, "Receita Demo"); setFeedback({ tone: "success", message: "Rateio recalculado; versões anteriores foram preservadas." }); }}><RefreshCcw className="size-4" />Recalcular rateio</Button></>} />
    <div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={!shares.some((item) => item.status === "CALCULATED")} onClick={() => { fundingRepository.confirmRevenueAllocation(id, "Receita Demo"); setFeedback({ tone: "success", message: "Rateio confirmado." }); }}>Confirmar rateio</Button><Button size="sm" variant="outline" onClick={() => setAdjustmentOpen(true)}>Registrar ajuste</Button><Button size="sm" variant="danger" disabled={!bankMovements.some((item) => item.movement.status === "FOUND")} onClick={reverse}>Estornar recebimento</Button></div>
    <FeedbackBanner feedback={feedback} onClose={() => setFeedback(null)} /><Tabs items={tabs} value={tab} onChange={setTab} />

    {tab === "summary" && <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiCard compact icon={Banknote} label="Valor previsto" value={formatCentsAmount(record.expectedInstallmentAmount)} /><KpiCard compact icon={CheckCircle2} label="Valor pago" value={formatCentsAmount(record.paidAmount)} /><KpiCard compact icon={Scale} label="Total apurado" value={formatCentsAmount(record.apuratedAmount)} /><KpiCard compact icon={AlertTriangle} label="Diferença" value={formatCentsAmount(record.componentDifference)} /></div><InfoGrid rows={[["Contrato", record.contractCode], ["Cliente", record.maskedClientName], ["Parcela", `${record.installmentNumber}/${record.totalInstallments}`], ["Vencimento", formatDate(record.dueDate)], ["Pagamento", formatDate(record.operationalPaymentDate)], ["Operador", record.financialOperator], ["Referência operacional", record.paymentReference.operationalReference], ["Referência bancária", record.paymentReference.bankReferences.join(", ") || "—"], ["Validação bancária", record.bankValidationStatus], ["Conciliação", record.reconciliationStatus]]} /></>}
    {tab === "components" && <><SimpleTable headers={["Principal", "Juros", "IOF", "Multa/mora", "Desconto", "Prejuízo", "Outros ajustes", "Total calculado", "Valor pago", "Diferença"]}><TableRow><MoneyCell value={record.principalAmount} /><MoneyCell value={record.interestAmount} /><MoneyCell value={record.iofAmount} /><MoneyCell value={record.penaltyAmount} /><MoneyCell value={record.discountAmount} /><MoneyCell value={record.lossAmount} /><MoneyCell value="0" /><MoneyCell value={record.apuratedAmount} /><MoneyCell value={record.paidAmount} /><MoneyCell value={record.componentDifference} /></TableRow></SimpleTable><div className="rounded-xl border bg-card/75 p-4 text-sm"><p className="font-medium">principal + juros + IOF + multa − desconto − prejuízo</p><div className="mt-2"><StatusBadge status={record.componentStatus} /></div><p className="mt-2 text-muted-foreground">Valores operacionais não são corrigidos automaticamente quando a soma diverge.</p></div></>}
    {tab === "bank" && <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiCard compact icon={Banknote} label="Valor operacional" value={formatCentsAmount(record.paidAmount)} /><KpiCard compact icon={CheckCircle2} label="Valor encontrado" value={formatCentsAmount(reconciled)} /><KpiCard compact icon={AlertTriangle} label="Diferença bancária" value={formatCentsAmount((cents(record.paidAmount) - cents(reconciled)).toString())} /><KpiCard compact icon={ShieldCheck} label="Status" value={record.bankValidationStatus.replaceAll("_", " ")} /></div><SimpleTable headers={["Conta", "Data", "Valor", "Associado", "Referência", "Descrição", "Responsável", "Conferência", "Status", "Observação"]}>{bankMovements.map(({ link, movement }) => <TableRow key={link.id}><TableCell>{movement.bankAccountId}</TableCell><TableCell>{formatDate(movement.movementDate)}</TableCell><MoneyCell value={movement.amount} /><MoneyCell value={link.amount} /><TableCell>{movement.transactionReference}</TableCell><TableCell>{movement.payerDescription}</TableCell><TableCell>{movement.checkedBy}</TableCell><TableCell>{formatDateTime(movement.checkedAt)}</TableCell><TableCell><StatusBadge status={movement.status} /></TableCell><TableCell>{movement.notes}</TableCell></TableRow>)}</SimpleTable><p className="rounded-xl border border-primary/20 bg-primary/5 p-4 text-sm text-muted-foreground">Esta aba lê a mesma conferência de Tesouraria &gt; Entradas. Qualquer alteração aparece nas duas visões imediatamente.</p></>}
    {tab === "allocation" && <><SimpleTable headers={["Fonte", "Investidor", "Aporte", "Participação", "Principal", "Juros", "IOF", "Desconto", "Prejuízo", "Total atribuído", "Status"]}>{shares.map((share) => { const allocation = state.contractFundingAllocations.find((item) => item.id === share.contractFundingAllocationId); const source = state.fundingSources.find((item) => item.id === allocation?.fundingSourceId); const investor = state.investors.find((item) => item.id === share.investorId); const contribution = state.contributions.find((item) => item.id === share.contributionId); const attributed = cents(share.principalShare) + cents(share.interestShare) + cents(share.penaltyShare) - cents(share.discountShare) - cents(share.lossShare); return <TableRow key={share.id}><TableCell>{source?.name ?? share.fundingSourceType}</TableCell><TableCell>{investor?.name ?? (share.fundingSourceType === "REMO_OWN_CAPITAL" ? "Capital próprio REMO" : "—")}</TableCell><TableCell>{contribution?.code ?? "—"}</TableCell><TableCell>{share.allocationBps} bps</TableCell><MoneyCell value={share.principalShare} /><MoneyCell value={share.interestShare} /><TableCell><span>{formatCentsAmount(share.iofShare)}</span><p className="text-xs text-amber-400">Regra a confirmar</p></TableCell><MoneyCell value={share.discountShare} /><MoneyCell value={share.lossShare} /><MoneyCell value={attributed.toString()} /><TableCell><StatusBadge status={share.status} /></TableCell></TableRow>; })}</SimpleTable><p className="rounded-xl border border-amber-400/20 bg-amber-400/5 p-4 text-sm text-muted-foreground">O IOF permanece separado e não é atribuído automaticamente a investidores nem ao capital próprio REMO.</p></>}
    {tab === "treasury" && <SimpleTable headers={["Data", "Tipo", "Natureza", "Valor", "Conta", "Referência", "Status", "Observação"]}>{treasury.map((item) => <TableRow key={item.id}><TableCell>{formatDate(item.date)}</TableCell><TableCell>{item.type.replaceAll("_", " ")}</TableCell><TableCell><StatusBadge status={item.direction} /></TableCell><MoneyCell value={item.amount} /><TableCell>{item.cashAccount}</TableCell><TableCell>{item.reference}</TableCell><TableCell><StatusBadge status={item.status} /></TableCell><TableCell>{item.notes}</TableCell></TableRow>)}</SimpleTable>}
    {tab === "divergences" && <SimpleTable headers={["Tipo", "Esperado", "Encontrado", "Diferença", "Situação", "Observações", "Ações"]}>{divergences.map((item) => <TableRow key={item.id}><TableCell>{revenueDivergenceLabels[item.type]}</TableCell><MoneyCell value={item.expectedAmount} /><MoneyCell value={item.actualAmount} /><MoneyCell value={item.differenceAmount} /><TableCell><StatusBadge status={item.status} /></TableCell><TableCell>{item.resolutionNotes ?? item.description}</TableCell><TableCell><div className="flex gap-1"><Button size="sm" variant="ghost" onClick={() => fundingRepository.updateRevenueDivergence(item.id, "INVESTIGATE", "Investigação iniciada no detalhe.", "Receita Demo")}>Investigar</Button><Button size="sm" variant="ghost" onClick={() => fundingRepository.updateRevenueDivergence(item.id, "JUSTIFY", "Exceção demonstrativa justificada.", "Receita Demo")}>Justificar</Button><Button size="sm" variant="ghost" onClick={() => fundingRepository.updateRevenueDivergence(item.id, "RESOLVE", "Divergência demonstrativa resolvida.", "Receita Demo")}>Resolver</Button></div></TableCell></TableRow>)}</SimpleTable>}
    {tab === "source" && <InfoGrid rows={[["Identificador operacional", record.operationalReceiptId], ["Identificador na Tesouraria", record.treasuryIncomingReceiptId ?? "—"], ["Origem futura", "ECON_AMORTIZACOES"], ["Competência", record.paymentReference.competence], ["Referência operacional", record.paymentReference.operationalReference], ["Descrição bancária", record.paymentReference.transactionDescriptions.join(", ") || "—"], ["Observação", record.observation], ["Criado em", formatDateTime(record.createdAt)], ["Atualizado em", formatDateTime(record.updatedAt)]]} />}
    {tab === "history" && <Card className="bg-card/75"><CardContent className="space-y-4 p-6">{history.map((item) => <div key={item.id}><p className="text-sm">{item.description}</p><p className="text-xs text-muted-foreground">{formatDateTime(item.date)} · {item.demoUser}</p></div>)}</CardContent></Card>}
    <AdjustmentModal open={adjustmentOpen} receiptId={id} onClose={() => setAdjustmentOpen(false)} onSaved={() => { setAdjustmentOpen(false); setFeedback({ tone: "success", message: "Ajuste criado na Tesouraria e apenas referenciado pela Receita." }); }} />
  </div>;
}

function AdjustmentModal({ open, receiptId, onClose, onSaved }: { open: boolean; receiptId: string; onClose: () => void; onSaved: () => void }) {
  const [value, setValue] = useState(""); const [direction, setDirection] = useState<"ENTRADA" | "SAIDA">("ENTRADA"); const [notes, setNotes] = useState(""); const amount = currencyInputToCents(value);
  return <Modal open={open} title="Registrar ajuste relacionado" description="O movimento pertence à Tesouraria; Receita mantém apenas o vínculo pelo mesmo recebimento." onClose={onClose} footer={<><Button variant="outline" onClick={onClose}>Cancelar</Button><Button disabled={amount === null || cents(amount) <= 0n} onClick={() => { if (amount) { fundingRepository.registerRevenueAdjustment(receiptId, amount, direction, { date: "2026-08-04", cashAccount: "Conta Caixa Demo 01", owner: "Receita Demo", notes }); onSaved(); } }}>Registrar ajuste</Button></>}><div className="grid gap-4"><FormField label="Natureza"><Select value={direction} onChange={(event) => setDirection(event.target.value as "ENTRADA" | "SAIDA")}><option value="ENTRADA">Entrada de ajuste</option><option value="SAIDA">Saída de ajuste</option></Select></FormField><FormField label="Valor"><Input value={value} onChange={(event) => setValue(event.target.value)} /></FormField><FormField label="Observação"><Textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></FormField></div></Modal>;
}

function InfoGrid({ rows }: { rows: [string, string][] }) { return <Card className="bg-card/75"><CardContent className="grid gap-4 p-6 sm:grid-cols-2 xl:grid-cols-3">{rows.map(([label, value]) => <div key={label}><p className="text-xs uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-1 text-sm font-medium">{value}</p></div>)}</CardContent></Card>; }
function SimpleTable({ headers, children }: { headers: string[]; children: React.ReactNode }) { return <Card className="overflow-hidden bg-card/75"><Table><TableHeader><TableRow>{headers.map((header) => <TableHead key={header}>{header}</TableHead>)}</TableRow></TableHeader><TableBody>{children}</TableBody></Table></Card>; }
function MoneyCell({ value }: { value: string }) { return <TableCell>{formatCentsAmount(value)}</TableCell>; }
