import { useEffect, useState } from "react";
import { FormField } from "@/components/common/FormField";
import { Modal } from "@/components/common/Modal";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { treasuryTypes } from "@/data/fundingOptions";
import { currencyInputToCents, formatCentsAmount } from "@/lib/formatters";
import type { Contribution, Investor, TreasuryDirection, TreasuryEntry, TreasuryEntryInput, TreasuryEntryType, TreasuryStatus } from "@/types/funding";

interface FormState { investorId: string; contributionId: string; type: TreasuryEntryType; direction: TreasuryDirection; amount: string; date: string; competence: string; cashAccount: string; status: TreasuryStatus; owner: string; reference: string; notes: string; }
function initial(entry?: TreasuryEntry): FormState { return entry ? { investorId: entry.investorId ?? "", contributionId: entry.contributionId ?? "", type: entry.type, direction: entry.direction, amount: formatCentsAmount(entry.amount), date: entry.date, competence: entry.competence, cashAccount: entry.cashAccount, status: entry.status, owner: entry.owner, reference: entry.reference, notes: entry.notes } : { investorId: "", contributionId: "", type: "ADJUSTMENT_IN", direction: "ENTRADA", amount: "", date: "2026-07-31", competence: "2026-07", cashAccount: "Conta Caixa Demo 01", status: "PENDENTE", owner: "Tesouraria Demo", reference: "", notes: "" }; }

export function TreasuryEntryFormModal({ open, entry, investors, contributions, onClose, onSave }: { open: boolean; entry?: TreasuryEntry; investors: Investor[]; contributions: Contribution[]; onClose: () => void; onSave: (input: TreasuryEntryInput) => void }) {
  const [form, setForm] = useState(() => initial(entry)); useEffect(() => setForm(initial(entry)), [entry, open]);
  const update = <K extends keyof FormState>(key: K, value: FormState[K]) => setForm((current) => ({ ...current, [key]: value })); const amount = currencyInputToCents(form.amount); const valid = amount !== null && BigInt(amount) > 0n && Boolean(form.date && form.owner && form.reference);
  const submit = () => { if (!valid || amount === null) return; onSave({ investorId: form.investorId || undefined, contributionId: form.contributionId || undefined, type: form.type, direction: form.direction, amount, date: form.date, competence: form.competence, cashAccount: form.cashAccount, status: form.status, owner: form.owner, reference: form.reference, notes: form.notes }); };
  return <Modal open={open} title={entry ? "Editar movimentação" : "Nova movimentação"} description="Movimentos confirmados são corrigidos por estorno, com trilha preservada." onClose={onClose} footer={<><Button variant="outline" onClick={onClose}>Cancelar</Button><Button disabled={!valid} onClick={submit}>Salvar movimento</Button></>}><div className="grid gap-4 sm:grid-cols-2">
    <FormField label="Tipo"><Select value={form.type} onChange={(event) => update("type", event.target.value as TreasuryEntryType)}>{treasuryTypes.map((type) => <option key={type} value={type}>{type.replaceAll("_", " ")}</option>)}</Select></FormField><FormField label="Natureza"><Select value={form.direction} onChange={(event) => update("direction", event.target.value as TreasuryDirection)}><option value="ENTRADA">Entrada</option><option value="SAIDA">Saída</option><option value="TRANSFERENCIA_INTERNA">Transferência interna</option></Select></FormField>
    <FormField label="Valor"><Input inputMode="decimal" value={form.amount} onChange={(event) => update("amount", event.target.value)} /></FormField><FormField label="Status"><Select value={form.status} onChange={(event) => update("status", event.target.value as TreasuryStatus)}><option value="PENDENTE">Pendente</option><option value="CONFIRMADO">Confirmado</option><option value="CANCELADO">Cancelado</option><option value="ESTORNADO">Estornado</option></Select></FormField>
    <FormField label="Data"><Input type="date" value={form.date} onChange={(event) => update("date", event.target.value)} /></FormField><FormField label="Competência"><Input type="month" value={form.competence} onChange={(event) => update("competence", event.target.value)} /></FormField>
    <FormField label="Investidor"><Select value={form.investorId} onChange={(event) => update("investorId", event.target.value)}><option value="">Sem vínculo</option>{investors.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></FormField><FormField label="Aporte"><Select value={form.contributionId} onChange={(event) => update("contributionId", event.target.value)}><option value="">Sem vínculo</option>{contributions.filter((item) => !form.investorId || item.investorId === form.investorId).map((item) => <option key={item.id} value={item.id}>{item.code}</option>)}</Select></FormField>
    <FormField label="Conta fictícia"><Input value={form.cashAccount} onChange={(event) => update("cashAccount", event.target.value)} /></FormField><FormField label="Responsável"><Input value={form.owner} onChange={(event) => update("owner", event.target.value)} /></FormField><FormField label="Referência"><Input value={form.reference} onChange={(event) => update("reference", event.target.value)} /></FormField><FormField label="Observações"><Textarea value={form.notes} onChange={(event) => update("notes", event.target.value)} /></FormField>
  </div></Modal>;
}
